// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-path
 * @version 15.4.2
 * @description Utility for file path
 * @typicalname utilPath
 * @license MIT
 */
'use strict'

const findupDir_ = require('./findupDir')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.findupDir = findupDir_

module.exports = {
  findupDir: findupDir_,
}
