// Code generated by coz. DO NOT EDIT.
/**
 * @description controller-mixin helpers
 * @namespace helpers
 * @memberof module:@the-/util-ctrl
 */
'use strict'

const omitLongString_ = require('./omitLongString')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.omitLongString = omitLongString_

module.exports = {
  omitLongString: omitLongString_,
}
