// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Tmp file creator
 * @license MIT
 * @module @the-/tmp
 * @typicalname tmp
 * @version 15.4.9
 */
'use strict'

const TheTmp_ = require('./TheTmp')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheTmp = TheTmp_
exports.create = create_

module.exports = default__
