// Code generated by coz. DO NOT EDIT.
/**
 * Image of the-components
 * @module @the-/ui-image
 */
'use strict'

import TheImage from './TheImage'
import TheImageStyle from './TheImageStyle'

export {
  TheImage,
  TheImageStyle,
}

export default {
      TheImage,
      TheImageStyle,
}
