// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Image of the-components
 * @module @the-/ui-image
 * @typicalname uiImage
 * @version 16.0.3
 */
'use strict'

import TheImage from './TheImage'

export {
  TheImage,
}
