// Code generated by coz. DO NOT EDIT.
/**
 * @description Image of the-components
 * @module @the-/ui-image
 * @typicalname uiImage
 * @version 15.4.8
 */
'use strict'

import TheImage from './TheImage'
import TheImageStyle from './TheImageStyle'

export {
  TheImage,
  TheImageStyle,
}

export default {
  TheImage,
  TheImageStyle,
}
