// Code generated by coz. DO NOT EDIT.
/**
 * @description Utility for site
 * @license MIT
 * @module @the-/util-site
 * @typicalname utilSite
 * @version 15.4.7
 */
'use strict'

const appendQueryToSearch_ = require('./appendQueryToSearch')
const countSuffix_ = require('./countSuffix')
const createStyleElement_ = require('./createStyleElement')
const envOf_ = require('./envOf')
const hasMoreFor_ = require('./hasMoreFor')
const isEmail_ = require('./isEmail')
const isPhoneNumber_ = require('./isPhoneNumber')
const normalizeString_ = require('./normalizeString')
const queryFromSearch_ = require('./queryFromSearch')
const refOf_ = require('./refOf')
const scrollToElement_ = require('./scrollToElement')
const seatAccess_ = require('./seatAccess')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.appendQueryToSearch = appendQueryToSearch_
exports.countSuffix = countSuffix_
exports.createStyleElement = createStyleElement_
exports.envOf = envOf_
exports.hasMoreFor = hasMoreFor_
exports.isEmail = isEmail_
exports.isPhoneNumber = isPhoneNumber_
exports.normalizeString = normalizeString_
exports.queryFromSearch = queryFromSearch_
exports.refOf = refOf_
exports.scrollToElement = scrollToElement_
exports.seatAccess = seatAccess_

module.exports = {
  appendQueryToSearch: appendQueryToSearch_,
  countSuffix: countSuffix_,
  createStyleElement: createStyleElement_,
  envOf: envOf_,
  hasMoreFor: hasMoreFor_,
  isEmail: isEmail_,
  isPhoneNumber: isPhoneNumber_,
  normalizeString: normalizeString_,
  queryFromSearch: queryFromSearch_,
  refOf: refOf_,
  scrollToElement: scrollToElement_,
  seatAccess: seatAccess_,
}
