// Code generated by coz. DO NOT EDIT.
/**
 * Alt text for the-components
 * @module the-alt
 */
'use strict'

import TheAlt from './TheAlt'
import TheAltStyle from './TheAltStyle'

export {
 TheAlt,
 TheAltStyle,
}
