// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Resize image files
 * @license MIT
 * @module @the-/resize
 * @typicalname resize
 * @version 15.4.16
 */
'use strict'

const TheResize_ = require('./TheResize')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheResize = TheResize_
exports.create = create_

module.exports = default__
