// Code generated by coz. DO NOT EDIT.
/**
 * Server controllers
 * @module controllers
 */
'use strict'

const AppCtrl_ = require('./AppCtrl')
const Ctrl_ = require('./Ctrl')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.AppCtrl = AppCtrl_
exports.Ctrl = Ctrl_

module.exports = {
  AppCtrl: AppCtrl_,
  Ctrl: Ctrl_,
}
