// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/video-converter
 * @namespace helpers
 */
'use strict'

const ffmpeg_ = require('./ffmpeg')
const ffprobe_ = require('./ffprobe')
const filenameFor_ = require('./filenameFor')
const isVideoSrc_ = require('./isVideoSrc')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ffmpeg = ffmpeg_
exports.ffprobe = ffprobe_
exports.filenameFor = filenameFor_
exports.isVideoSrc = isVideoSrc_

module.exports = {
  ffmpeg: ffmpeg_,
  ffprobe: ffprobe_,
  filenameFor: filenameFor_,
  isVideoSrc: isVideoSrc_,
}
