// Code generated by coz. DO NOT EDIT.
/**
 * Container of the-components
 * @module the-container
 */
'use strict'

import TheContainer from './TheContainer'
import TheContainerStyle from './TheContainerStyle'

export {
 TheContainer,
 TheContainerStyle,
}
