// Code generated by coz. DO NOT EDIT.
/**
 * Tab for the-components
 * @module the-tab
 */
'use strict'

import TheTab from './TheTab'
import TheTabStyle from './TheTabStyle'

export {
 TheTab,
 TheTabStyle,
}
