// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/spell
 * @namespace helpers
 */
'use strict'

const SpellCache_ = require('./SpellCache')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.SpellCache = SpellCache_

module.exports = {
  SpellCache: SpellCache_,
}
