// Code generated by coz. DO NOT EDIT.
/**
 * en locales
 * @module en
 */
'use strict'

const app_ = require('./app')
const buttons_ = require('./buttons')
const errors_ = require('./errors')
const messages_ = require('./messages')
const org_ = require('./org')
const titles_ = require('./titles')
const toasts_ = require('./toasts')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.app = app_
exports.buttons = buttons_
exports.errors = errors_
exports.messages = messages_
exports.org = org_
exports.titles = titles_
exports.toasts = toasts_

module.exports = {
  app: app_,
  buttons: buttons_,
  errors: errors_,
  messages: messages_,
  org: org_,
  titles: titles_,
  toasts: toasts_,
}
