// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Constant variables
 * @memberOf module:@the-/server
 * @namespace constants
 */
'use strict'

const ClientStatuses_ = require('./ClientStatuses')
const DefaultValues_ = require('./DefaultValues')
const IOEvents_ = require('./IOEvents')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ClientStatuses = ClientStatuses_
exports.DefaultValues = DefaultValues_
exports.IOEvents = IOEvents_

module.exports = {
  ClientStatuses: ClientStatuses_,
  DefaultValues: DefaultValues_,
  IOEvents: IOEvents_,
}
