// Code generated by coz. DO NOT EDIT.
'use strict'

const DefaultValues_ = require('./DefaultValues')
const IOEvents_ = require('./IOEvents')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.DefaultValues = DefaultValues_
exports.IOEvents = IOEvents_

module.exports = {
  DefaultValues: DefaultValues_,
  IOEvents: IOEvents_,
}
