// Code generated by coz. DO NOT EDIT.
/**
 * Video for the-components
 * @module @the-/ui-video
 */
'use strict'

import TheVideo from './TheVideo'
import TheVideoStyle from './TheVideoStyle'

export {
  TheVideo,
  TheVideoStyle,
}

export default {
      TheVideo,
      TheVideoStyle,
}
