// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Video for the-components
 * @module @the-/ui-video
 * @typicalname uiVideo
 * @version 15.4.8
 */
'use strict'

import TheVideo from './TheVideo'
import TheVideoStyle from './TheVideoStyle'

export {
  TheVideo,
  TheVideoStyle,
}

export default {
  TheVideo,
  TheVideoStyle,
}
