// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Video for the-components
 * @module @the-/ui-video
 * @typicalname uiVideo
 * @version 16.0.0
 */
'use strict'

import TheVideo from './TheVideo'

export {
  TheVideo,
}
