// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description connector functions
 * @memberOf module:@the-/server
 * @namespace connectors
 */
'use strict'

const IOConnector_ = require('./IOConnector')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.IOConnector = IOConnector_

module.exports = {
  IOConnector: IOConnector_,
}
