// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/error
 * @version 15.4.0
 * @description Error for the-framework
 * @typicalname error
 * @license MIT
 */
'use strict'

const TheConflictError_ = require('./TheConflictError')
const TheError_ = require('./TheError')
const TheExpiredError_ = require('./TheExpiredError')
const TheForbiddenError_ = require('./TheForbiddenError')
const TheGoneError_ = require('./TheGoneError')
const TheInvalidParameterError_ = require('./TheInvalidParameterError')
const TheNotAcceptableError_ = require('./TheNotAcceptableError')
const TheNotFoundError_ = require('./TheNotFoundError')
const TheRequestTimeoutError_ = require('./TheRequestTimeoutError')
const TheServerRottenError_ = require('./TheServerRottenError')
const TheUnauthorizedError_ = require('./TheUnauthorizedError')
const create_ = require('./create')
const define_ = require('./define')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheConflictError = TheConflictError_
exports.TheError = TheError_
exports.TheExpiredError = TheExpiredError_
exports.TheForbiddenError = TheForbiddenError_
exports.TheGoneError = TheGoneError_
exports.TheInvalidParameterError = TheInvalidParameterError_
exports.TheNotAcceptableError = TheNotAcceptableError_
exports.TheNotFoundError = TheNotFoundError_
exports.TheRequestTimeoutError = TheRequestTimeoutError_
exports.TheServerRottenError = TheServerRottenError_
exports.TheUnauthorizedError = TheUnauthorizedError_
exports.create = create_
exports.define = define_

module.exports = {
  TheConflictError: TheConflictError_,
  TheError: TheError_,
  TheExpiredError: TheExpiredError_,
  TheForbiddenError: TheForbiddenError_,
  TheGoneError: TheGoneError_,
  TheInvalidParameterError: TheInvalidParameterError_,
  TheNotAcceptableError: TheNotAcceptableError_,
  TheNotFoundError: TheNotFoundError_,
  TheRequestTimeoutError: TheRequestTimeoutError_,
  TheServerRottenError: TheServerRottenError_,
  TheUnauthorizedError: TheUnauthorizedError_,
  create: create_,
  define: define_,
}
