// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Setting manager for the-framework
 * @license MIT
 * @module @the-/setting
 * @typicalname setting
 * @version 15.4.13
 */
'use strict'

const TheSetting_ = require('./TheSetting')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSetting = TheSetting_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_

module.exports = default__
