// Code generated by coz. DO NOT EDIT.
/**
 * @description Client mixin functions
 * @memberOf module:@the-/driver-mongo
 * @namespace mixins
 */
'use strict'

const mongoMix_ = require('./mongoMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.mongoMix = mongoMix_

module.exports = {
  mongoMix: mongoMix_,
}
