// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Count implementations
 * @memberof module:@the-/metrics.counters
 * @namespace counters
 */
'use strict'

const ClassMethodCallCounter_ = require('./ClassMethodCallCounter')
const Counter_ = require('./Counter')
const ObjectMethodCallCounter_ = require('./ObjectMethodCallCounter')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ClassMethodCallCounter = ClassMethodCallCounter_
exports.Counter = Counter_
exports.ObjectMethodCallCounter = ObjectMethodCallCounter_

module.exports = {
  ClassMethodCallCounter: ClassMethodCallCounter_,
  Counter: Counter_,
  ObjectMethodCallCounter: ObjectMethodCallCounter_,
}
