// Code generated by coz. DO NOT EDIT.
/**
 * Count implementations
 * @module counters
 */
'use strict'

const Counter_ = require('./Counter')
const MethodCallCounter_ = require('./MethodCallCounter')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Counter = Counter_
exports.MethodCallCounter = MethodCallCounter_

module.exports = {
  Counter: Counter_,
  MethodCallCounter: MethodCallCounter_,
}
