// Code generated by coz. DO NOT EDIT.
/**
 * Component to show caught errors
 * @module the-caught
 */
'use strict'

import TheCaught from './TheCaught'
import TheCaughtCatcher from './TheCaughtCatcher'
import TheCaughtStyle from './TheCaughtStyle'

export {
  TheCaught,
  TheCaughtCatcher,
  TheCaughtStyle,
}
