// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberOf module:@the-/seat
 * @namespace mixins
 */
'use strict'

const lockMix_ = require('./lockMix')
const scopeMix_ = require('./scopeMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.lockMix = lockMix_
exports.scopeMix = scopeMix_

module.exports = {
  lockMix: lockMix_,
  scopeMix: scopeMix_,
}
