// Code generated by coz. DO NOT EDIT.
/**
 * Abstract scenes
 * @module scenes
 */
'use strict'

const CallScene_ = require('./CallScene')
const DetailScene_ = require('./DetailScene')
const InputScene_ = require('./InputScene')
const ListScene_ = require('./ListScene')
const Scene_ = require('./Scene')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.CallScene = CallScene_
exports.DetailScene = DetailScene_
exports.InputScene = InputScene_
exports.ListScene = ListScene_
exports.Scene = Scene_

module.exports = {
  CallScene: CallScene_,
  DetailScene: DetailScene_,
  InputScene: InputScene_,
  ListScene: ListScene_,
  Scene: Scene_,
}
