// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Container of the-components
 * @module @the-/ui-container
 * @typicalname uiContainer
 * @version 16.0.0
 */
'use strict'

import TheContainer from './TheContainer'

export {
  TheContainer,
}
