// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Container of the-components
 * @module @the-/ui-container
 * @typicalname uiContainer
 * @version 15.4.11
 */
'use strict'

import TheContainer from './TheContainer'
import TheContainerStyle from './TheContainerStyle'

export {
  TheContainer,
  TheContainerStyle,
}

export default {
  TheContainer,
  TheContainerStyle,
}
