// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Facebook utility for the-framework
 * @license MIT
 * @module @the-/facebook
 * @typicalname facebook
 * @version 15.4.10
 */
'use strict'

const Constants_ = require('./Constants')
const TheFacebook_ = require('./TheFacebook')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Constants = Constants_
exports.TheFacebook = TheFacebook_
exports.create = create_

module.exports = default__
