// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-copyboard
 * @typicalname uiCopyboard
 * @version 15.4.5
 * @description Component for clip-to-copy
 */
'use strict'

import TheCopyboard from './TheCopyboard'
import TheCopyboardStyle from './TheCopyboardStyle'

export {
  TheCopyboard,
  TheCopyboardStyle,
}

export default {
  TheCopyboard,
  TheCopyboardStyle,
}
