// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Chat UI of the-components
 * @module @the-/ui-chat
 * @typicalname uiChat
 * @version 15.4.17
 */
'use strict'

import TheChat from './TheChat'
import TheChatForm from './TheChatForm'
import TheChatTimeLine from './TheChatTimeLine'
import TheChatTimeLineItem from './TheChatTimeLineItem'

export {
  TheChat,
  TheChatForm,
  TheChatTimeLine,
  TheChatTimeLineItem,
}
