// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-chat
 * @typicalname uiChat
 * @version 15.4.0
 * @description Chat UI of the-components
 */
'use strict'

import TheChat from './TheChat'
import TheChatForm from './TheChatForm'
import TheChatStyle from './TheChatStyle'
import TheChatTimeLine from './TheChatTimeLine'
import TheChatTimeLineItem from './TheChatTimeLineItem'

export {
  TheChat,
  TheChatForm,
  TheChatStyle,
  TheChatTimeLine,
  TheChatTimeLineItem,
}

export default {
  TheChat,
  TheChatForm,
  TheChatStyle,
  TheChatTimeLine,
  TheChatTimeLineItem,
}
