// Code generated by coz. DO NOT EDIT.
'use strict'

const sendMock_ = require('./sendMock')
const sendSMTP_ = require('./sendSMTP')
const sendSendgrid_ = require('./sendSendgrid')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.sendMock = sendMock_
exports.sendSMTP = sendSMTP_
exports.sendSendgrid = sendSendgrid_

module.exports = {
  sendMock: sendMock_,
  sendSMTP: sendSMTP_,
  sendSendgrid: sendSendgrid_,
}
