// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Flickable viewer of the-components
 * @module @the-/ui-flick
 * @typicalname uiFlick
 * @version 15.4.12
 */
'use strict'

import TheFlick from './TheFlick'
import TheFlickImage from './TheFlickImage'
import TheFlickStyle from './TheFlickStyle'

export {
  TheFlick,
  TheFlickImage,
  TheFlickStyle,
}

export default {
  TheFlick,
  TheFlickImage,
  TheFlickStyle,
}
