// Code generated by coz. DO NOT EDIT.
/**
 * Flickable viewer of the-components
 * @module @the-/ui-flick
 */
'use strict'

const TheFlick_ = require('./TheFlick')
const TheFlickImage_ = require('./TheFlickImage')
const TheFlickStyle_ = require('./TheFlickStyle')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheFlick = TheFlick_
exports.TheFlickImage = TheFlickImage_
exports.TheFlickStyle = TheFlickStyle_

module.exports = {
  TheFlick: TheFlick_,
  TheFlickImage: TheFlickImage_,
  TheFlickStyle: TheFlickStyle_,
}
