// Code generated by coz. DO NOT EDIT.
/**
 * @namespace helpers
 * @memberOf module:@the-/lint
 * @access protected
 * @description Helper functions
 */
'use strict'

const LintCache_ = require('./LintCache')
const parseHelper_ = require('./parseHelper')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.LintCache = LintCache_
exports.parseHelper = parseHelper_

module.exports = {
  LintCache: LintCache_,
  parseHelper: parseHelper_,
}
