// Code generated by coz. DO NOT EDIT.
/**
 * @description Client for the-server
 * @license MIT
 * @module @the-/client
 * @typicalname client
 * @version 15.4.11
 */
'use strict'

const TheClient_ = require('./TheClient')
const constants_ = require('./constants')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheClient = TheClient_
exports.constants = constants_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_

module.exports = default__
