// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/loc
 * @version 15.4.2
 * @description Locale resolver for the-framework
 * @typicalname loc
 * @license MIT
 */
'use strict'

const TheLoc_ = require('./TheLoc')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheLoc = TheLoc_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
