// Code generated by coz. DO NOT EDIT.
/**
 * Locale resolver for the-framework
 * @module @the-/loc
 */
'use strict'

const TheLoc_ = require('./TheLoc')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheLoc = TheLoc_
exports.create = create_

module.exports = default__
