// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Embed camera component
 * @module @the-/ui-cam
 * @typicalname uiCam
 * @version 15.4.12
 */
'use strict'

import TheCam from './TheCam'
import TheCamInput from './TheCamInput'
import TheCamStyle from './TheCamStyle'

export {
  TheCam,
  TheCamInput,
  TheCamStyle,
}

export default {
  TheCam,
  TheCamInput,
  TheCamStyle,
}
