// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Embed camera component
 * @module @the-/ui-cam
 * @typicalname uiCam
 * @version 16.0.10
 */
'use strict'

import TheCam from './TheCam'
import TheCamInput from './TheCamInput'

export {
  TheCam,
  TheCamInput,
}
