// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Utility for controllers
 * @license MIT
 * @module @the-/util-ctrl
 * @typicalname utilCtrl
 * @version 15.4.12
 */
'use strict'

const helpers_ = require('./helpers')
const withDebug_ = require('./withDebug')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.helpers = helpers_
exports.withDebug = withDebug_

module.exports = {
  helpers: helpers_,
  withDebug: withDebug_,
}
