// Code generated by coz. DO NOT EDIT.
/**
 * Dialog for the-components
 * @module the-dialog
 */
'use strict'

import TheConfirmDialog from './TheConfirmDialog'
import TheDialog from './TheDialog'
import TheDialogStyle from './TheDialogStyle'
import TheOkDialog from './TheOkDialog'
import TheYesNoDialog from './TheYesNoDialog'

export {
  TheConfirmDialog,
  TheDialog,
  TheDialogStyle,
  TheOkDialog,
  TheYesNoDialog,
}
