// Code generated by coz. DO NOT EDIT.
/**
 * Html of the-components
 * @module @the-/html
 */
'use strict'

import TheHtml from './TheHtml'
import TheHtmlStyle from './TheHtmlStyle'

export {
  TheHtml,
  TheHtmlStyle,
}
