// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Tab for the-components
 * @module @the-/ui-tab
 * @typicalname uiTab
 * @version 15.4.17
 */
'use strict'

import TheTab from './TheTab'
import TheTabButton from './TheTabButton'
import TheTabContent from './TheTabContent'
import TheTabStyle from './TheTabStyle'

export {
  TheTab,
  TheTabButton,
  TheTabContent,
  TheTabStyle,
}
