// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Tab for the-components
 * @module @the-/ui-tab
 * @typicalname uiTab
 * @version 16.0.0
 */
'use strict'

import TheTab from './TheTab'
import TheTabButton from './TheTabButton'
import TheTabContent from './TheTabContent'

export {
  TheTab,
  TheTabButton,
  TheTabContent,
}
