// Code generated by coz. DO NOT EDIT.
/**
 * Sequelize driver for the-framework
 * @module @the-/driver-sequelize
 */
'use strict'

const TheDriverSequelize_ = require('./TheDriverSequelize')
const constants_ = require('./constants')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const parsing_ = require('./parsing')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheDriverSequelize = TheDriverSequelize_
exports.constants = constants_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_
exports.parsing = parsing_

module.exports = default__
