// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Sequelize driver for the-framework
 * @license MIT
 * @module @the-/driver-sequelize
 * @typicalname driverSequelize
 * @version 16.0.8
 */
'use strict'

const TheDriverSequelize_ = require('./TheDriverSequelize')
const constants_ = require('./constants')
const converters_ = require('./converters')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const modeling_ = require('./modeling')
const parsing_ = require('./parsing')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheDriverSequelize = TheDriverSequelize_
exports.constants = constants_
exports.converters = converters_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_
exports.modeling = modeling_
exports.parsing = parsing_

module.exports = default__
