// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Toast of the-components
 * @module @the-/ui-toast
 * @typicalname uiToast
 * @version 15.4.11
 */
'use strict'

import TheToast from './TheToast'
import TheToastGroup from './TheToastGroup'
import TheToastStyle from './TheToastStyle'

export {
  TheToast,
  TheToastGroup,
  TheToastStyle,
}
