// Code generated by coz. DO NOT EDIT.
/**
 * @namespace helpers
 * @memberOf module:@the-/loc
 * @access protected
 * @description Helper functions
 */
'use strict'

const mergedLocales_ = require('./mergedLocales')
const resolveInScope_ = require('./resolveInScope')
const toCompoundLocale_ = require('./toCompoundLocale')
const validateLocales_ = require('./validateLocales')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.mergedLocales = mergedLocales_
exports.resolveInScope = resolveInScope_
exports.toCompoundLocale = toCompoundLocale_
exports.validateLocales = validateLocales_

module.exports = {
  mergedLocales: mergedLocales_,
  resolveInScope: resolveInScope_,
  toCompoundLocale: toCompoundLocale_,
  validateLocales: validateLocales_,
}
