// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/video-converter
 * @version 15.4.5
 * @description Video file converter
 * @typicalname videoConverter
 * @license MIT
 */
'use strict'

const TheVideoConverter_ = require('./TheVideoConverter')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheVideoConverter = TheVideoConverter_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_

module.exports = default__
