// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/video-converter
 * @version 15.4.3
 * @description Video file converter
 * @typicalname videoConverter
 * @license MIT
 */
'use strict'

const TheVideoConverter_ = require('./TheVideoConverter')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheVideoConverter = TheVideoConverter_
exports.create = create_

module.exports = default__
