// Code generated by coz. DO NOT EDIT.
/**
 * Dialogs Component
 */
'use strict'

import React from 'react'
import {
  ConnectionRetryDialog,
} from '../stateful'

class Dialogs extends React.Component {
  render () {
    return (
      <>
        <ConnectionRetryDialog/>
      </>
    )
  }
}

export default Dialogs
