// Code generated by coz. DO NOT EDIT.
/**
 * Layout Components
 * @module layouts
 */
'use strict'

import Dialogs from './Dialogs'
import Footer from './Footer'
import Header from './Header'
import Toasts from './Toasts'

export {
 Dialogs,
 Footer,
 Header,
 Toasts,
}
