// Code generated by coz. DO NOT EDIT.
/**
 * @description Layout Components
 * @memberof module:client.ui
 * @namespace layouts
 */
'use strict'

import Dialogs from './Dialogs'
import Footer from './Footer'
import Header from './Header'
import Toasts from './Toasts'

export {
  Dialogs,
  Footer,
  Header,
  Toasts,
}

export default {
  Dialogs,
  Footer,
  Header,
  Toasts,
}
