// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/mixin-stream
 * @version 15.4.0
 * @description Mixins for stream
 * @typicalname mixinStream
 * @license MIT
 */
'use strict'

const compose_ = require('./compose')
const withDebug_ = require('./withDebug')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.compose = compose_
exports.withDebug = withDebug_

module.exports = {
  compose: compose_,
  withDebug: withDebug_,
}
