// Code generated by coz. DO NOT EDIT.
/**
 * @description Info of the-component
 * @module @the-/ui-info
 * @typicalname uiInfo
 * @version 15.4.5
 */
'use strict'

import TheInfo from './TheInfo'
import TheInfoStyle from './TheInfoStyle'

export {
  TheInfo,
  TheInfoStyle,
}

export default {
  TheInfo,
  TheInfoStyle,
}
