// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Info of the-component
 * @module @the-/ui-info
 * @typicalname uiInfo
 * @version 16.0.1
 */
'use strict'

import TheInfo from './TheInfo'

export {
  TheInfo,
}
