// Code generated by coz. DO NOT EDIT.
/**
 * @description Repeatable of the-component
 * @module @the-/ui-repeatable
 * @typicalname uiRepeatable
 * @version 15.4.5
 */
'use strict'

import TheRepeatable from './TheRepeatable'
import TheRepeatableStyle from './TheRepeatableStyle'

export {
  TheRepeatable,
  TheRepeatableStyle,
}

export default {
  TheRepeatable,
  TheRepeatableStyle,
}
