// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description iFrame of the-components
 * @module @the-/ui-frame
 * @typicalname uiFrame
 * @version 15.4.12
 */
'use strict'

import TheFrame from './TheFrame'
import TheFrameStyle from './TheFrameStyle'

export {
  TheFrame,
  TheFrameStyle,
}
