// Code generated by coz. DO NOT EDIT.
/**
 * @description Constant variables
 * @memberOf module:@the-/ast
 * @namespace constants
 */
'use strict'

const NodeTypes_ = require('./NodeTypes')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.NodeTypes = NodeTypes_

module.exports = {
  NodeTypes: NodeTypes_,
}
