// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module mixins
 */
'use strict'

const sequelizeMix_ = require('./sequelizeMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.sequelizeMix = sequelizeMix_

module.exports = {
  sequelizeMix: sequelizeMix_,
}
