// Code generated by coz. DO NOT EDIT.
/**
 * @description Buildin resources
 * @memberOf module:@the-/db
 * @namespace resources
 */
'use strict'

const TheLogResource_ = require('./TheLogResource')
const TheSchemaResource_ = require('./TheSchemaResource')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheLogResource = TheLogResource_
exports.TheSchemaResource = TheSchemaResource_

module.exports = {
  TheLogResource: TheLogResource_,
  TheSchemaResource: TheSchemaResource_,
}
