// Code generated by coz. DO NOT EDIT.
/**
 * Spin of the-components
 * @module @the-/spin
 */
'use strict'

import TheSpin from './TheSpin'
import TheSpinStyle from './TheSpinStyle'

export {
  TheSpin,
  TheSpinStyle,
}

export default {
      TheSpin,
      TheSpinStyle,
}
