// Code generated by coz. DO NOT EDIT.
/**
 * @description Component to show caught errors
 * @module @the-/ui-caught
 * @typicalname uiCaught
 * @version 15.4.7
 */
'use strict'

import TheCaught from './TheCaught'
import TheCaughtCatcher from './TheCaughtCatcher'
import TheCaughtStyle from './TheCaughtStyle'

export {
  TheCaught,
  TheCaughtCatcher,
  TheCaughtStyle,
}

export default {
  TheCaught,
  TheCaughtCatcher,
  TheCaughtStyle,
}
