// Code generated by coz. DO NOT EDIT.
/**
 * Component to show caught errors
 * @module @the-/ui-caught
 */
'use strict'

import TheCaught from './TheCaught'
import TheCaughtCatcher from './TheCaughtCatcher'
import TheCaughtStyle from './TheCaughtStyle'

export {
  TheCaught,
  TheCaughtCatcher,
  TheCaughtStyle,
}

export default {
      TheCaught,
      TheCaughtCatcher,
      TheCaughtStyle,
}
