// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Component to show caught errors
 * @module @the-/ui-caught
 * @typicalname uiCaught
 * @version 16.0.1
 */
'use strict'

import TheCaught from './TheCaught'
import TheCaughtCatcher from './TheCaughtCatcher'

export {
  TheCaught,
  TheCaughtCatcher,
}
