// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description React context for the-components
 * @license MIT
 * @module @the-/context
 * @typicalname context
 * @version 18.0.0
 */
'use strict'

const TheContext_ = require('./TheContext')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheContext = TheContext_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
