// Code generated by coz. DO NOT EDIT.
/**
 * React context for the-components
 * @module @the-/context
 */
'use strict'

const TheContext_ = require('./TheContext')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheContext = TheContext_
exports.create = create_

module.exports = default__
