// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Icon of the-components
 * @module @the-/ui-icon
 * @typicalname uiIcon
 * @version 16.0.2
 */
'use strict'

import TheIcon from './TheIcon'

export {
  TheIcon,
}
