// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-icon
 * @typicalname uiIcon
 * @version 15.4.2
 * @description Icon of the-components
 */
'use strict'

import TheIcon from './TheIcon'
import TheIconStyle from './TheIconStyle'

export {
  TheIcon,
  TheIconStyle,
}

export default {
  TheIcon,
  TheIconStyle,
}
