// Code generated by coz. DO NOT EDIT.
/**
 * @description Buildin stores
 * @memberOf module:@the-/server
 * @namespace stores
 */
'use strict'

const ConnectionStore_ = require('./ConnectionStore')
const SessionStore_ = require('./SessionStore')
const Store_ = require('./Store')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ConnectionStore = ConnectionStore_
exports.SessionStore = SessionStore_
exports.Store = Store_

module.exports = {
  ConnectionStore: ConnectionStore_,
  SessionStore: SessionStore_,
  Store: Store_,
}
