// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Spin of the-components
 * @module @the-/ui-spin
 * @typicalname uiSpin
 * @version 15.5.1
 */
'use strict'

import TheSpin from './TheSpin'
import TheSpinStyle from './TheSpinStyle'

export {
  TheSpin,
  TheSpinStyle,
}
