// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Spin of the-components
 * @module @the-/ui-spin
 * @typicalname uiSpin
 * @version 16.0.0
 */
'use strict'

import TheSpin from './TheSpin'

export {
  TheSpin,
}
