// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-spin
 * @typicalname uiSpin
 * @version 15.4.3
 * @description Spin of the-components
 */
'use strict'

import TheSpin from './TheSpin'
import TheSpinStyle from './TheSpinStyle'

export {
  TheSpin,
  TheSpinStyle,
}

export default {
  TheSpin,
  TheSpinStyle,
}
