// Code generated by coz. DO NOT EDIT.
/**
 * controller-mixin helpers
 * @module helpers
 */
'use strict'

const getAllPropertyDescriptors_ = require('./getAllPropertyDescriptors')
const instanceMethodNamesFor_ = require('./instanceMethodNamesFor')
const omitLongString_ = require('./omitLongString')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.getAllPropertyDescriptors = getAllPropertyDescriptors_
exports.instanceMethodNamesFor = instanceMethodNamesFor_
exports.omitLongString = omitLongString_

module.exports = {
  getAllPropertyDescriptors: getAllPropertyDescriptors_,
  instanceMethodNamesFor: instanceMethodNamesFor_,
  omitLongString: omitLongString_,
}
