// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Facade to wrap scopes
 * @license MIT
 * @module @the-/facade-scope
 * @typicalname facadeScope
 * @version 16.1.25
 */
'use strict'

const busyAccessFor_ = require('./busyAccessFor')
const countsAccessFor_ = require('./countsAccessFor')
const entitiesAccessFor_ = require('./entitiesAccessFor')
const entityAccessFor_ = require('./entityAccessFor')
const entryAccessFor_ = require('./entryAccessFor')
const filterAccessFor_ = require('./filterAccessFor')
const idAccessFor_ = require('./idAccessFor')
const moreAccessFor_ = require('./moreAccessFor')
const operations_ = require('./operations')
const pageAccessFor_ = require('./pageAccessFor')
const readyAccessFor_ = require('./readyAccessFor')
const resultAccessFor_ = require('./resultAccessFor')
const sortAccessFor_ = require('./sortAccessFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.busyAccessFor = busyAccessFor_
exports.countsAccessFor = countsAccessFor_
exports.entitiesAccessFor = entitiesAccessFor_
exports.entityAccessFor = entityAccessFor_
exports.entryAccessFor = entryAccessFor_
exports.filterAccessFor = filterAccessFor_
exports.idAccessFor = idAccessFor_
exports.moreAccessFor = moreAccessFor_
exports.operations = operations_
exports.pageAccessFor = pageAccessFor_
exports.readyAccessFor = readyAccessFor_
exports.resultAccessFor = resultAccessFor_
exports.sortAccessFor = sortAccessFor_

module.exports = {
  busyAccessFor: busyAccessFor_,
  countsAccessFor: countsAccessFor_,
  entitiesAccessFor: entitiesAccessFor_,
  entityAccessFor: entityAccessFor_,
  entryAccessFor: entryAccessFor_,
  filterAccessFor: filterAccessFor_,
  idAccessFor: idAccessFor_,
  moreAccessFor: moreAccessFor_,
  operations: operations_,
  pageAccessFor: pageAccessFor_,
  readyAccessFor: readyAccessFor_,
  resultAccessFor: resultAccessFor_,
  sortAccessFor: sortAccessFor_,
}
