// Code generated by coz. DO NOT EDIT.
/**
 * @description Facade to wrap scopes
 * @license MIT
 * @module @the-/facade-scope
 * @typicalname facadeScope
 * @version 15.4.11
 */
'use strict'

const busyFor_ = require('./busyFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.busyFor = busyFor_

module.exports = {
  busyFor: busyFor_,
}
