// Code generated by coz. DO NOT EDIT.
/**
 * @description Client mixin functions
 * @namespace mixins
 */
'use strict'

const infoMix_ = require('./infoMix')
const pingPongMix_ = require('./pingPongMix')
const streamMix_ = require('./streamMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.infoMix = infoMix_
exports.pingPongMix = pingPongMix_
exports.streamMix = streamMix_

module.exports = {
  infoMix: infoMix_,
  pingPongMix: pingPongMix_,
  streamMix: streamMix_,
}
