// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Client mixin functions
 * @memberOf module:@the-/client
 * @namespace mixins
 */
'use strict'

const infoMix_ = require('./infoMix')
const pingPongMix_ = require('./pingPongMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.infoMix = infoMix_
exports.pingPongMix = pingPongMix_

module.exports = {
  infoMix: infoMix_,
  pingPongMix: pingPongMix_,
}
