// Code generated by coz. DO NOT EDIT.
/**
 * @description Class mixins
 * @memberof module:@the-/rtc
 * @namespace mixins
 */
'use strict'

const httpMix_ = require('./httpMix')
const ioMix_ = require('./ioMix')
const sfuMix_ = require('./sfuMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.httpMix = httpMix_
exports.ioMix = ioMix_
exports.sfuMix = sfuMix_

module.exports = {
  httpMix: httpMix_,
  ioMix: ioMix_,
  sfuMix: sfuMix_,
}
