// Code generated by coz. DO NOT EDIT.
/**
 * Class mixins
 * @module mixins
 */
'use strict'

const httpMix_ = require('./httpMix')
const ioMix_ = require('./ioMix')
const sfuMix_ = require('./sfuMix')
const turnMix_ = require('./turnMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.httpMix = httpMix_
exports.ioMix = ioMix_
exports.sfuMix = sfuMix_
exports.turnMix = turnMix_

module.exports = {
  httpMix: httpMix_,
  ioMix: ioMix_,
  sfuMix: sfuMix_,
  turnMix: turnMix_,
}
