// Code generated by coz. DO NOT EDIT.
/**
 * Browser entrypoint for the-framework
 * @module @the-/entrypoint
 */
'use strict'

const history_ = require('./history')
const mount_ = require('./mount')
const online_ = require('./online')
const patch_ = require('./patch')
const quelize_ = require('./quelize')
const secure_ = require('./secure')
const singleton_ = require('./singleton')
const workers_ = require('./workers')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.history = history_
exports.mount = mount_
exports.online = online_
exports.patch = patch_
exports.quelize = quelize_
exports.secure = secure_
exports.singleton = singleton_
exports.workers = workers_

module.exports = {
  history: history_,
  mount: mount_,
  online: online_,
  patch: patch_,
  quelize: quelize_,
  secure: secure_,
  singleton: singleton_,
  workers: workers_,
}
