// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/entrypoint
 * @namespace helpers
 */
'use strict'

const createStyleElement_ = require('./createStyleElement')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.createStyleElement = createStyleElement_

module.exports = {
  createStyleElement: createStyleElement_,
}
