// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-dialog
 * @typicalname uiDialog
 * @version 15.4.3
 * @description Dialog for the-components
 */
'use strict'

import TheConfirmDialog from './TheConfirmDialog'
import TheDialog from './TheDialog'
import TheDialogStyle from './TheDialogStyle'
import TheOkDialog from './TheOkDialog'
import TheYesNoDialog from './TheYesNoDialog'

export {
  TheConfirmDialog,
  TheDialog,
  TheDialogStyle,
  TheOkDialog,
  TheYesNoDialog,
}

export default {
  TheConfirmDialog,
  TheDialog,
  TheDialogStyle,
  TheOkDialog,
  TheYesNoDialog,
}
