// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/code
 * @version 15.5.8
 * @description Code formatter of the-frameworks
 * @typicalname code
 * @license MIT
 */
'use strict'

const TheCode_ = require('./TheCode')
const constants_ = require('./constants')
const create_ = require('./create')
const helpers_ = require('./helpers')
const parsers_ = require('./parsers')
const processors_ = require('./processors')
const run_ = require('./run')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheCode = TheCode_
exports.constants = constants_
exports.create = create_
exports.helpers = helpers_
exports.parsers = parsers_
exports.processors = processors_
exports.run = run_

module.exports = default__
