// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/jsdoc
 * @version 15.4.11
 * @description JSDoc generator
 * @typicalname jsdoc
 * @license MIT
 */
'use strict'

const JSDoc_ = require('./JSDoc')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.JSDoc = JSDoc_
exports.create = create_

module.exports = default__
