// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/jsdoc
 * @version 15.4.3
 * @description JSDoc generator
 * @typicalname jsdoc
 * @license MIT
 */
'use strict'

const Jsdoc_ = require('./Jsdoc')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Jsdoc = Jsdoc_
exports.create = create_

module.exports = default__
