// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Constants for the-components
 * @license MIT
 * @module @the-/const-code
 * @typicalname constCode
 * @version 15.4.8
 */
'use strict'

const PrettierConfig_ = require('./PrettierConfig')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.PrettierConfig = PrettierConfig_

module.exports = {
  PrettierConfig: PrettierConfig_,
}
