// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Constants for the-components
 * @license MIT
 * @module @the-/const-code
 * @typicalname constCode
 * @version 15.5.2
 */
'use strict'

const JSDocPreferredTypes_ = require('./JSDocPreferredTypes')
const PrettierConfig_ = require('./PrettierConfig')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.JSDocPreferredTypes = JSDocPreferredTypes_
exports.PrettierConfig = PrettierConfig_

module.exports = {
  JSDocPreferredTypes: JSDocPreferredTypes_,
  PrettierConfig: PrettierConfig_,
}
