// Code generated by coz. DO NOT EDIT.
/**
 * @namespace helpers
 * @memberOf module:@the-/file
 * @access protected
 * @description Helper functions
 */
'use strict'

const sortProperties_ = require('./sortProperties')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.sortProperties = sortProperties_

module.exports = {
  sortProperties: sortProperties_,
}
