// Code generated by coz. DO NOT EDIT.
/**
 * @description Browser utility for the-framework
 * @license MIT
 * @module @the-/window
 * @typicalname window
 * @version 15.5.2
 */
'use strict'

const get_ = require('./get')
const line_ = require('./line')
const once_ = require('./once')
const reload_ = require('./reload')
const rescue_ = require('./rescue')
const set_ = require('./set')
const show_ = require('./show')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.get = get_
exports.line = line_
exports.once = once_
exports.reload = reload_
exports.rescue = rescue_
exports.set = set_
exports.show = show_

module.exports = {
  get: get_,
  line: line_,
  once: once_,
  reload: reload_,
  rescue: rescue_,
  set: set_,
  show: show_,
}
