// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Browser utility for the-framework
 * @license MIT
 * @module @the-/window
 * @typicalname window
 * @version 15.8.3
 */
'use strict'

const detain_ = require('./detain')
const full_ = require('./full')
const get_ = require('./get')
const line_ = require('./line')
const once_ = require('./once')
const open_ = require('./open')
const reload_ = require('./reload')
const rescue_ = require('./rescue')
const set_ = require('./set')
const show_ = require('./show')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.detain = detain_
exports.full = full_
exports.get = get_
exports.line = line_
exports.once = once_
exports.open = open_
exports.reload = reload_
exports.rescue = rescue_
exports.set = set_
exports.show = show_

module.exports = {
  detain: detain_,
  full: full_,
  get: get_,
  line: line_,
  once: once_,
  open: open_,
  reload: reload_,
  rescue: rescue_,
  set: set_,
  show: show_,
}
