// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Spell checker
 * @license MIT
 * @module @the-/spell
 * @typicalname spell
 * @version 15.6.18
 */
'use strict'

const TheSpell_ = require('./TheSpell')
const Words_ = require('./Words')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSpell = TheSpell_
exports.Words = Words_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
