// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberOf module:@the-/date
 * @namespace mixins
 */
'use strict'

const addMix_ = require('./addMix')
const endOfMix_ = require('./endOfMix')
const getMix_ = require('./getMix')
const momentMix_ = require('./momentMix')
const setMix_ = require('./setMix')
const startOfMix_ = require('./startOfMix')
const subtractMix_ = require('./subtractMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.addMix = addMix_
exports.endOfMix = endOfMix_
exports.getMix = getMix_
exports.momentMix = momentMix_
exports.setMix = setMix_
exports.startOfMix = startOfMix_
exports.subtractMix = subtractMix_

module.exports = {
  addMix: addMix_,
  endOfMix: endOfMix_,
  getMix: getMix_,
  momentMix: momentMix_,
  setMix: setMix_,
  startOfMix: startOfMix_,
  subtractMix: subtractMix_,
}
