// Code generated by coz. DO NOT EDIT.
'use strict'

const handleUnknownOptions_ = require('./handleUnknownOptions')
const toLowerKeys_ = require('./toLowerKeys')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.handleUnknownOptions = handleUnknownOptions_
exports.toLowerKeys = toLowerKeys_

module.exports = {
  handleUnknownOptions: handleUnknownOptions_,
  toLowerKeys: toLowerKeys_,
}
