// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-hamburger
 * @typicalname uiHamburger
 * @version 15.4.0
 * @description Hamburger menu for the-components
 */
'use strict'

import TheHamburger from './TheHamburger'
import TheHamburgerStyle from './TheHamburgerStyle'

export {
  TheHamburger,
  TheHamburgerStyle,
}

export default {
  TheHamburger,
  TheHamburgerStyle,
}
