// Code generated by coz. DO NOT EDIT.
/**
 * Hamburger menu for the-components
 * @module @the-/ui-hamburger
 */
'use strict'

import TheHamburger from './TheHamburger'
import TheHamburgerStyle from './TheHamburgerStyle'

export {
  TheHamburger,
  TheHamburgerStyle,
}

export default {
  TheHamburger,
  TheHamburgerStyle,
}
