// Code generated by coz. DO NOT EDIT.
/**
 * Bar of the-components
 * @module @the-/bar
 */
'use strict'

import TheActionBar from './TheActionBar'
import TheBar from './TheBar'
import TheBarStyle from './TheBarStyle'

export {
  TheActionBar,
  TheBar,
  TheBarStyle,
}
