// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Input of the-components
 * @module @the-/ui-input
 * @typicalname uiInput
 * @version 15.5.16
 */
'use strict'

import TheInput from './TheInput'
import TheInputCheckbox from './TheInputCheckbox'
import TheInputDate from './TheInputDate'
import TheInputNumber from './TheInputNumber'
import TheInputPassword from './TheInputPassword'
import TheInputPinCode from './TheInputPinCode'
import TheInputRadio from './TheInputRadio'
import TheInputRange from './TheInputRange'
import TheInputSearch from './TheInputSearch'
import TheInputSelect from './TheInputSelect'
import TheInputSlider from './TheInputSlider'
import TheInputStyle from './TheInputStyle'
import TheInputTag from './TheInputTag'
import TheInputText from './TheInputText'
import TheInputTextArea from './TheInputTextArea'
import TheInputToggle from './TheInputToggle'
import TheInputUpload from './TheInputUpload'
import helpers from './helpers'
import patterns from './patterns'

export {
  TheInput,
  TheInputCheckbox,
  TheInputDate,
  TheInputNumber,
  TheInputPassword,
  TheInputPinCode,
  TheInputRadio,
  TheInputRange,
  TheInputSearch,
  TheInputSelect,
  TheInputSlider,
  TheInputStyle,
  TheInputTag,
  TheInputText,
  TheInputTextArea,
  TheInputToggle,
  TheInputUpload,
  helpers,
  patterns,
}

export default {
  TheInput,
  TheInputCheckbox,
  TheInputDate,
  TheInputNumber,
  TheInputPassword,
  TheInputPinCode,
  TheInputRadio,
  TheInputRange,
  TheInputSearch,
  TheInputSelect,
  TheInputSlider,
  TheInputStyle,
  TheInputTag,
  TheInputText,
  TheInputTextArea,
  TheInputToggle,
  TheInputUpload,
  helpers,
  patterns,
}
