// Code generated by coz. DO NOT EDIT.
/**
 * Geo map for the-components
 * @module @the-/ui-map
 */
'use strict'

import TheMap from './TheMap'
import TheMapMarker from './TheMapMarker'
import TheMapPositionInput from './TheMapPositionInput'
import TheMapStyle from './TheMapStyle'

export {
  TheMap,
  TheMapMarker,
  TheMapPositionInput,
  TheMapStyle,
}

export default {
      TheMap,
      TheMapMarker,
      TheMapPositionInput,
      TheMapStyle,
}
