// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-map
 * @typicalname uiMap
 * @version 15.4.5
 * @description Geo map for the-components
 */
'use strict'

import TheMap from './TheMap'
import TheMapMarker from './TheMapMarker'
import TheMapPositionInput from './TheMapPositionInput'
import TheMapStyle from './TheMapStyle'

export {
  TheMap,
  TheMapMarker,
  TheMapPositionInput,
  TheMapStyle,
}

export default {
  TheMap,
  TheMapMarker,
  TheMapPositionInput,
  TheMapStyle,
}
