// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description State scope for the-store
 * @license MIT
 * @module @the-/scope
 * @typicalname scope
 * @version 15.4.10
 */
'use strict'

const TheScope_ = require('./TheScope')
const create_ = require('./create')
const scopes_ = require('./scopes')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheScope = TheScope_
exports.create = create_
exports.scopes = scopes_

module.exports = default__
