// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Demo of the-lib packages
 * @license MIT
 * @module @the-/demo-lib
 * @typicalname demoLib
 * @version 15.4.9
 */
'use strict'

const TheDemoLib_ = require('./TheDemoLib')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheDemoLib = TheDemoLib_
exports.create = create_

module.exports = default__
