// Code generated by coz. DO NOT EDIT.
'use strict'

const TheDemoLib_ = require('./TheDemoLib')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheDemoLib = TheDemoLib_
exports.create = create_

module.exports = default__
