// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Constant variables
 * @memberOf module:@the-/client
 * @namespace constants
 */
'use strict'

const IOEvents_ = require('./IOEvents')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.IOEvents = IOEvents_

module.exports = {
  IOEvents: IOEvents_,
}
