// Code generated by coz. DO NOT EDIT.
/**
 * Table for the-components
 * @module @the-/table
 */
'use strict'

import TheTable from './TheTable'
import TheTableStyle from './TheTableStyle'

export {
  TheTable,
  TheTableStyle,
}

export default {
      TheTable,
      TheTableStyle,
}
