// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Constant variables
 * @memberof module:@the-/rtc
 * @namespace constants
 */
'use strict'

const ChannelNames_ = require('./ChannelNames')
const IOEvents_ = require('./IOEvents')
const PeerEvents_ = require('./PeerEvents')
const TopologyTypes_ = require('./TopologyTypes')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ChannelNames = ChannelNames_
exports.IOEvents = IOEvents_
exports.PeerEvents = PeerEvents_
exports.TopologyTypes = TopologyTypes_

module.exports = {
  ChannelNames: ChannelNames_,
  IOEvents: IOEvents_,
  PeerEvents: PeerEvents_,
  TopologyTypes: TopologyTypes_,
}
