// Code generated by coz. DO NOT EDIT.
/**
 * Router of the-components
 * @module @the-/router
 */
'use strict'

const TheRouter_ = require('./TheRouter')
const TheRouterStyle_ = require('./TheRouterStyle')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRouter = TheRouter_
exports.TheRouterStyle = TheRouterStyle_

module.exports = {
  TheRouter: TheRouter_,
  TheRouterStyle: TheRouterStyle_,
}
