// Code generated by coz. DO NOT EDIT.
/**
 * Router of the-components
 * @module the-router
 */
'use strict'

import TheRouter from './TheRouter'
import TheRouterStyle from './TheRouterStyle'

export {
 TheRouter,
 TheRouterStyle,
}
