// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Rule functions
 * @memberOf module:@the-/lint
 * @namespace rules
 */
'use strict'

const callRule_ = require('./callRule')
const contentRule_ = require('./contentRule')
const decorateRule_ = require('./decorateRule')
const depsRule_ = require('./depsRule')
const filenameRule_ = require('./filenameRule')
const moduleRule_ = require('./moduleRule')
const packageRule_ = require('./packageRule')
const propRule_ = require('./propRule')
const usageRule_ = require('./usageRule')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.callRule = callRule_
exports.contentRule = contentRule_
exports.decorateRule = decorateRule_
exports.depsRule = depsRule_
exports.filenameRule = filenameRule_
exports.moduleRule = moduleRule_
exports.packageRule = packageRule_
exports.propRule = propRule_
exports.usageRule = usageRule_

module.exports = {
  callRule: callRule_,
  contentRule: contentRule_,
  decorateRule: decorateRule_,
  depsRule: depsRule_,
  filenameRule: filenameRule_,
  moduleRule: moduleRule_,
  packageRule: packageRule_,
  propRule: propRule_,
  usageRule: usageRule_,
}
