// Code generated by coz. DO NOT EDIT.
/**
 * Build in Lint Rules
 * @module rules
 */
'use strict'

const callRule_ = require('./callRule')
const contentRule_ = require('./contentRule')
const decorateRule_ = require('./decorateRule')
const depsRule_ = require('./depsRule')
const filenameRule_ = require('./filenameRule')
const moduleRule_ = require('./moduleRule')
const propRule_ = require('./propRule')
const usageRule_ = require('./usageRule')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.callRule = callRule_
exports.contentRule = contentRule_
exports.decorateRule = decorateRule_
exports.depsRule = depsRule_
exports.filenameRule = filenameRule_
exports.moduleRule = moduleRule_
exports.propRule = propRule_
exports.usageRule = usageRule_

module.exports = {
  callRule: callRule_,
  contentRule: contentRule_,
  decorateRule: decorateRule_,
  depsRule: depsRule_,
  filenameRule: filenameRule_,
  moduleRule: moduleRule_,
  propRule: propRule_,
  usageRule: usageRule_,
}
