// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/assert
 * @version 15.4.2
 * @description Assert for the-framework
 * @typicalname assert
 * @license MIT
 */
'use strict'

const TheAssert_ = require('./TheAssert')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheAssert = TheAssert_
exports.create = create_

module.exports = default__
