// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Header of the-components
 * @module @the-/ui-header
 * @typicalname uiHeader
 * @version 16.0.1
 */
'use strict'

import TheHeader from './TheHeader'

export {
  TheHeader,
}
