// Code generated by coz. DO NOT EDIT.
/**
 * Header of the-components
 * @module @the-/ui-header
 */
'use strict'

import TheHeader from './TheHeader'
import TheHeaderStyle from './TheHeaderStyle'

export {
  TheHeader,
  TheHeaderStyle,
}

export default {
      TheHeader,
      TheHeaderStyle,
}
