// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-header
 * @typicalname uiHeader
 * @version 15.4.2
 * @description Header of the-components
 */
'use strict'

import TheHeader from './TheHeader'
import TheHeaderStyle from './TheHeaderStyle'

export {
  TheHeader,
  TheHeaderStyle,
}

export default {
  TheHeader,
  TheHeaderStyle,
}
