// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/icon
 * @namespace helpers
 */
'use strict'

const applier_ = require('./applier')
const drawer_ = require('./drawer')
const writer_ = require('./writer')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.applier = applier_
exports.drawer = drawer_
exports.writer = writer_

module.exports = {
  applier: applier_,
  drawer: drawer_,
  writer: writer_,
}
