// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/controller
 * @version 15.4.3
 * @description Base of the-controllers
 * @typicalname controller
 * @license MIT
 */
'use strict'

const Invocation_ = require('./Invocation')
const TheCtrl_ = require('./TheCtrl')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Invocation = Invocation_
exports.TheCtrl = TheCtrl_
exports.create = create_

module.exports = default__
