// Code generated by coz. DO NOT EDIT.
/**
 * @description Dom utility for the-framework
 * @license MIT
 * @module @the-/util-dom
 * @typicalname utilDom
 * @version 15.4.11
 */
'use strict'

const byId_ = require('./byId')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.byId = byId_

module.exports = {
  byId: byId_,
}
