// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Dom utility for the-framework
 * @license MIT
 * @module @the-/util-dom
 * @typicalname utilDom
 * @version 15.5.2
 */
'use strict'

const byId_ = require('./byId')
const injectScript_ = require('./injectScript')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.byId = byId_
exports.injectScript = injectScript_

module.exports = {
  byId: byId_,
  injectScript: injectScript_,
}
