// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-db
 * @version 15.4.0
 * @description Utility for the-db
 * @typicalname utilDb
 * @license MIT
 */
'use strict'

const evalScript_ = require('./evalScript')
const toLowerKeys_ = require('./toLowerKeys')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.evalScript = evalScript_
exports.toLowerKeys = toLowerKeys_

module.exports = {
  evalScript: evalScript_,
  toLowerKeys: toLowerKeys_,
}
