// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Utility for server
 * @license MIT
 * @module @the-/util-server
 * @typicalname utilServer
 * @version 15.4.16
 */
'use strict'

const changeExt_ = require('./changeExt')
const generateFile_ = require('./generateFile')
const isBase64_ = require('./isBase64')
const nameFile_ = require('./nameFile')
const pipeToFile_ = require('./pipeToFile')
const saveBase64_ = require('./saveBase64')
const saveBase64Image_ = require('./saveBase64Image')
const valuesFromEntity_ = require('./valuesFromEntity')
const waitFor_ = require('./waitFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.changeExt = changeExt_
exports.generateFile = generateFile_
exports.isBase64 = isBase64_
exports.nameFile = nameFile_
exports.pipeToFile = pipeToFile_
exports.saveBase64 = saveBase64_
exports.saveBase64Image = saveBase64Image_
exports.valuesFromEntity = valuesFromEntity_
exports.waitFor = waitFor_

module.exports = {
  changeExt: changeExt_,
  generateFile: generateFile_,
  isBase64: isBase64_,
  nameFile: nameFile_,
  pipeToFile: pipeToFile_,
  saveBase64: saveBase64_,
  saveBase64Image: saveBase64Image_,
  valuesFromEntity: valuesFromEntity_,
  waitFor: waitFor_,
}
