// Code generated by coz. DO NOT EDIT.
/**
 * @namespace helpers
 * @memberOf module:@the-/context
 * @access protected
 * @description Client helper functions
 */
'use strict'

const contextEntryFor_ = require('./contextEntryFor')
const contextRootFor_ = require('./contextRootFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.contextEntryFor = contextEntryFor_
exports.contextRootFor = contextRootFor_

module.exports = {
  contextEntryFor: contextEntryFor_,
  contextRootFor: contextRootFor_,
}
