// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Bar of the-components
 * @module @the-/ui-bar
 * @typicalname uiBar
 * @version 16.0.1
 */
'use strict'

import TheActionBar from './TheActionBar'
import TheBar from './TheBar'

export {
  TheActionBar,
  TheBar,
}
