// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Bar of the-components
 * @module @the-/ui-bar
 * @typicalname uiBar
 * @version 15.5.4
 */
'use strict'

import TheActionBar from './TheActionBar'
import TheBar from './TheBar'
import TheBarStyle from './TheBarStyle'

export {
  TheActionBar,
  TheBar,
  TheBarStyle,
}
