// Code generated by coz. DO NOT EDIT.
/**
 * @description Bar of the-components
 * @module @the-/ui-bar
 * @typicalname uiBar
 * @version 15.4.8
 */
'use strict'

import TheActionBar from './TheActionBar'
import TheBar from './TheBar'
import TheBarStyle from './TheBarStyle'

export {
  TheActionBar,
  TheBar,
  TheBarStyle,
}

export default {
  TheActionBar,
  TheBar,
  TheBarStyle,
}
