// Code generated by coz. DO NOT EDIT.
/**
 * Icon of the-components
 * @module @the-/icon
 */
'use strict'

import TheIcon from './TheIcon'
import TheIconStyle from './TheIconStyle'

export {
  TheIcon,
  TheIconStyle,
}
