// Code generated by coz. DO NOT EDIT.
/**
 * @description Icon generator
 * @license MIT
 * @module @the-/icon
 * @typicalname icon
 * @version 15.4.12
 */
'use strict'

const TheIcon_ = require('./TheIcon')
const Themes_ = require('./Themes')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheIcon = TheIcon_
exports.Themes = Themes_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
