// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Live demo of the-components
 * @module @the-/ui-demo
 * @typicalname uiDemo
 * @version 16.0.0
 */
'use strict'

import TheComponentDemo from './TheComponentDemo'

export {
  TheComponentDemo,
}
