// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-demo
 * @typicalname uiDemo
 * @version 15.4.5
 * @description Live demo of the-components
 */
'use strict'

import TheComponentDemo from './TheComponentDemo'

export {
  TheComponentDemo,
}

export default {
  TheComponentDemo,
}
