// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Conditional renderer for the-components
 * @module @the-/ui-condition
 * @typicalname uiCondition
 * @version 15.4.10
 */
'use strict'

import TheCondition from './TheCondition'
import TheConditionStyle from './TheConditionStyle'

export {
  TheCondition,
  TheConditionStyle,
}

export default {
  TheCondition,
  TheConditionStyle,
}
