// Code generated by coz. DO NOT EDIT.
/**
 * Mongo driver for the-db
 * @module the-driver-mongo
 */
'use strict'

import MongoDriver from './MongoDriver'
import create from './create'
import mixins from './mixins'

export {
 MongoDriver,
 create,
 mixins,
}
