// Code generated by coz. DO NOT EDIT.
/**
 * Random delay timer
 * @module the-jitter
 */
'use strict'

const TheJitter_ = require('./TheJitter')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheJitter = TheJitter_
exports.create = create_

module.exports = default__
