// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module parsing
 */
'use strict'

const parseAttributeName_ = require('./parseAttributeName')
const parseFilter_ = require('./parseFilter')
const parseSort_ = require('./parseSort')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.parseAttributeName = parseAttributeName_
exports.parseFilter = parseFilter_
exports.parseSort = parseSort_

module.exports = {
  parseAttributeName: parseAttributeName_,
  parseFilter: parseFilter_,
  parseSort: parseSort_,
}
