// Code generated by coz. DO NOT EDIT.
/**
 * Body of the-components
 * @module @the-/body
 */
'use strict'

import TheBody from './TheBody'
import TheBodyStyle from './TheBodyStyle'

export {
  TheBody,
  TheBodyStyle,
}
