// Code generated by coz. DO NOT EDIT.
/**
 * Alt text for the-components
 * @module @the-/ui-alt
 */
'use strict'

import TheAlt from './TheAlt'
import TheAltStyle from './TheAltStyle'

export {
  TheAlt,
  TheAltStyle,
}

export default {
      TheAlt,
      TheAltStyle,
}
