// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-alt
 * @typicalname uiAlt
 * @version 15.4.3
 * @description Alt text for the-components
 */
'use strict'

import TheAlt from './TheAlt'
import TheAltStyle from './TheAltStyle'

export {
  TheAlt,
  TheAltStyle,
}

export default {
  TheAlt,
  TheAltStyle,
}
