// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Alt text for the-components
 * @module @the-/ui-alt
 * @typicalname uiAlt
 * @version 16.0.1
 */
'use strict'

import TheAlt from './TheAlt'

export {
  TheAlt,
}
