// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/seal
 * @version 15.4.5
 * @description Encrypt json object with master password
 * @typicalname seal
 * @license MIT
 */
'use strict'

const TheSeal_ = require('./TheSeal')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSeal = TheSeal_
exports.create = create_

module.exports = default__
