// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module constant variables
 */
'use strict'

const MetaColumnNames_ = require('./MetaColumnNames')
const MetaColumnNamesReversed_ = require('./MetaColumnNamesReversed')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.MetaColumnNames = MetaColumnNames_
exports.MetaColumnNamesReversed = MetaColumnNamesReversed_

module.exports = {
  MetaColumnNames: MetaColumnNames_,
  MetaColumnNamesReversed: MetaColumnNamesReversed_,
}
