// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/util-path
 * @namespace helpers
 */
'use strict'

const exists_ = require('./exists')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.exists = exists_

module.exports = {
  exists: exists_,
}
