// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Password util for the-framework
 * @license MIT
 * @module @the-/password
 * @typicalname password
 * @version 15.4.14
 */
'use strict'

const ThePassword_ = require('./ThePassword')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ThePassword = ThePassword_
exports.create = create_

module.exports = default__
