// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/queue
 * @version 15.4.3
 * @description Queue for the-framework
 * @typicalname queue
 * @license MIT
 */
'use strict'

const TheQueue_ = require('./TheQueue')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheQueue = TheQueue_
exports.create = create_

module.exports = default__
