// Code generated by coz. DO NOT EDIT.
/**
 * Info of the-component
 * @module the-info
 */
'use strict'

import TheInfo from './TheInfo'
import TheInfoStyle from './TheInfoStyle'

export {
 TheInfo,
 TheInfoStyle,
}
