// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-button
 * @typicalname uiButton
 * @version 15.4.0
 * @description Button of the-components
 */
'use strict'

import TheButton from './TheButton'
import TheButtonGroup from './TheButtonGroup'
import TheButtonStyle from './TheButtonStyle'

export {
  TheButton,
  TheButtonGroup,
  TheButtonStyle,
}

export default {
  TheButton,
  TheButtonGroup,
  TheButtonStyle,
}
