// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Button of the-components
 * @module @the-/ui-button
 * @typicalname uiButton
 * @version 16.0.2
 */
'use strict'

import TheButton from './TheButton'
import TheButtonGroup from './TheButtonGroup'

export {
  TheButton,
  TheButtonGroup,
}
