// Code generated by coz. DO NOT EDIT.
/**
 * Button of the-components
 * @module @the-/ui-button
 */
'use strict'

import TheButton from './TheButton'
import TheButtonGroup from './TheButtonGroup'
import TheButtonStyle from './TheButtonStyle'

export {
  TheButton,
  TheButtonGroup,
  TheButtonStyle,
}

export default {
  TheButton,
  TheButtonGroup,
  TheButtonStyle,
}
