// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Body of the-components
 * @module @the-/ui-body
 * @typicalname uiBody
 * @version 16.0.0
 */
'use strict'

import TheBody from './TheBody'

export {
  TheBody,
}
