// Code generated by coz. DO NOT EDIT.
/**
 * @description Body of the-components
 * @module @the-/ui-body
 * @typicalname uiBody
 * @version 15.4.5
 */
'use strict'

import TheBody from './TheBody'
import TheBodyStyle from './TheBodyStyle'

export {
  TheBody,
  TheBodyStyle,
}

export default {
  TheBody,
  TheBodyStyle,
}
