// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description RTC server for the-frameworks
 * @license MIT
 * @module @the-/rtc
 * @typicalname rtc
 * @version 15.7.0
 */
'use strict'

const TheRTC_ = require('./TheRTC')
const constants_ = require('./constants')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRTC = TheRTC_
exports.constants = constants_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_

module.exports = default__
