// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Chart for the-components
 * @module @the-/ui-chart
 * @typicalname uiChart
 * @version 15.4.11
 */
'use strict'

import TheChart from './TheChart'
import TheChartStyle from './TheChartStyle'

export {
  TheChart,
  TheChartStyle,
}

export default {
  TheChart,
  TheChartStyle,
}
