// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Chart for the-components
 * @module @the-/ui-chart
 * @typicalname uiChart
 * @version 15.4.14
 */
'use strict'

import TheChart from './TheChart'

export {
  TheChart,
}
