// Code generated by coz. DO NOT EDIT.
/**
 * Form of the-components
 * @module @the-/form
 */
'use strict'

import TheForm from './TheForm'
import TheFormBinder from './TheFormBinder'
import TheFormStyle from './TheFormStyle'

export {
  TheForm,
  TheFormBinder,
  TheFormStyle,
}
