// Code generated by coz. DO NOT EDIT.
/**
 * @description Keyboard component
 * @module @the-/ui-keyboard
 * @typicalname uiKeyboard
 * @version 15.4.8
 */
'use strict'

import TheKeyboard from './TheKeyboard'
import TheKeyboardButton from './TheKeyboardButton'
import TheKeyboardStyle from './TheKeyboardStyle'

export {
  TheKeyboard,
  TheKeyboardButton,
  TheKeyboardStyle,
}

export default {
  TheKeyboard,
  TheKeyboardButton,
  TheKeyboardStyle,
}
