// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Keyboard component
 * @module @the-/ui-keyboard
 * @typicalname uiKeyboard
 * @version 16.0.0
 */
'use strict'

import TheKeyboard from './TheKeyboard'
import TheKeyboardButton from './TheKeyboardButton'

export {
  TheKeyboard,
  TheKeyboardButton,
}
