// Code generated by coz. DO NOT EDIT.
/**
 * Keyboard component
 * @module @the-/ui-keyboard
 */
'use strict'

import TheKeyboard from './TheKeyboard'
import TheKeyboardButton from './TheKeyboardButton'
import TheKeyboardStyle from './TheKeyboardStyle'

export {
  TheKeyboard,
  TheKeyboardButton,
  TheKeyboardStyle,
}

export default {
      TheKeyboard,
      TheKeyboardButton,
      TheKeyboardStyle,
}
