// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-color
 * @version 15.4.3
 * @description Color utility for the-framework
 * @typicalname utilColor
 * @license MIT
 */
'use strict'

const colorWithAlpha_ = require('./colorWithAlpha')
const colorWithText_ = require('./colorWithText')
const rotatedColorsFor_ = require('./rotatedColorsFor')
const textColorFor_ = require('./textColorFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.colorWithAlpha = colorWithAlpha_
exports.colorWithText = colorWithText_
exports.rotatedColorsFor = rotatedColorsFor_
exports.textColorFor = textColorFor_

module.exports = {
  colorWithAlpha: colorWithAlpha_,
  colorWithText: colorWithText_,
  rotatedColorsFor: rotatedColorsFor_,
  textColorFor: textColorFor_,
}
