// Code generated by coz. DO NOT EDIT.
/**
 * @memberof module:@the-/rtc
 * @description Class mixins
 * @namespace mixins
 */
'use strict'

const assertMix_ = require('./assertMix')
const channelMix_ = require('./channelMix')
const mediaMix_ = require('./mediaMix')
const peerMix_ = require('./peerMix')
const promiseMix_ = require('./promiseMix')
const serializeMix_ = require('./serializeMix')
const socketMix_ = require('./socketMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.assertMix = assertMix_
exports.channelMix = channelMix_
exports.mediaMix = mediaMix_
exports.peerMix = peerMix_
exports.promiseMix = promiseMix_
exports.serializeMix = serializeMix_
exports.socketMix = socketMix_

module.exports = {
  assertMix: assertMix_,
  channelMix: channelMix_,
  mediaMix: mediaMix_,
  peerMix: peerMix_,
  promiseMix: promiseMix_,
  serializeMix: serializeMix_,
  socketMix: socketMix_,
}
