// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Mixin functions
 * @memberOf module:@the-/resource
 * @namespace mixins
 */
'use strict'

const listenMix_ = require('./listenMix')
const queueMix_ = require('./queueMix')
const writeOnceMix_ = require('./writeOnceMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.listenMix = listenMix_
exports.queueMix = queueMix_
exports.writeOnceMix = writeOnceMix_

module.exports = {
  listenMix: listenMix_,
  queueMix: queueMix_,
  writeOnceMix: writeOnceMix_,
}
