// Code generated by coz. DO NOT EDIT.
/**
 * @namespace helpers
 * @memberOf module:@the-/stream
 * @access protected
 * @description Helper functions
 */
'use strict'

const generatorFromReadable_ = require('./generatorFromReadable')
const webStreams_ = require('./webStreams')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.generatorFromReadable = generatorFromReadable_
exports.webStreams = webStreams_

module.exports = {
  generatorFromReadable: generatorFromReadable_,
  webStreams: webStreams_,
}
