// Code generated by coz. DO NOT EDIT.
/**
 * @namespace state
 * @memberOf module:@the-/state
 * @access protected
 * @description State classes
 */
'use strict'

const RootState_ = require('./RootState')
const ScopedState_ = require('./ScopedState')
const State_ = require('./State')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.RootState = RootState_
exports.ScopedState = ScopedState_
exports.State = State_

module.exports = {
  RootState: RootState_,
  ScopedState: ScopedState_,
  State: State_,
}
