// Code generated by coz. DO NOT EDIT.
/**
 * Action handler for the-framework
 * @module the-handle
 */
'use strict'

const TheHandle_ = require('./TheHandle')
const contexts_ = require('./contexts')
const create_ = require('./create')
const helpers_ = require('./helpers')
const inject_ = require('./inject')
const toHandleSceneClass_ = require('./toHandleSceneClass')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheHandle = TheHandle_
exports.contexts = contexts_
exports.create = create_
exports.helpers = helpers_
exports.inject = inject_
exports.toHandleSceneClass = toHandleSceneClass_

module.exports = default__
