// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/handle
 * @version 15.4.3
 * @description Action handler for the-framework
 * @typicalname handle
 * @license MIT
 */
'use strict'

const TheHandle_ = require('./TheHandle')
const create_ = require('./create')
const helpers_ = require('./helpers')
const toHandleSceneClass_ = require('./toHandleSceneClass')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheHandle = TheHandle_
exports.create = create_
exports.helpers = helpers_
exports.toHandleSceneClass = toHandleSceneClass_

module.exports = default__
