// Code generated by coz. DO NOT EDIT.
/**
 * @description Refactoring tool for the-components
 * @license MIT
 * @module @the-/refactor
 * @typicalname refactor
 * @version 15.4.8
 */
'use strict'

const TheRefactor_ = require('./TheRefactor')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRefactor = TheRefactor_
exports.create = create_

module.exports = default__
