// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Notification api wrapper
 * @license MIT
 * @module @the-/notify
 * @typicalname notify
 * @version 15.8.2
 */
'use strict'

const askNotification_ = require('./askNotification')
const showNotification_ = require('./showNotification')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.askNotification = askNotification_
exports.showNotification = showNotification_

module.exports = {
  askNotification: askNotification_,
  showNotification: showNotification_,
}
