// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Menu of the-components
 * @module @the-/ui-menu
 * @typicalname uiMenu
 * @version 15.4.14
 */
'use strict'

import TheDropdownMenu from './TheDropdownMenu'
import TheMenu from './TheMenu'
import TheMenuItem from './TheMenuItem'
import TheMenuStyle from './TheMenuStyle'

export {
  TheDropdownMenu,
  TheMenu,
  TheMenuItem,
  TheMenuStyle,
}

export default {
  TheDropdownMenu,
  TheMenu,
  TheMenuItem,
  TheMenuStyle,
}
