// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Menu of the-components
 * @module @the-/ui-menu
 * @typicalname uiMenu
 * @version 16.0.0
 */
'use strict'

import TheDropdownMenu from './TheDropdownMenu'
import TheMenu from './TheMenu'
import TheMenuItem from './TheMenuItem'

export {
  TheDropdownMenu,
  TheMenu,
  TheMenuItem,
}
