// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Hand write painting
 * @module @the-/ui-paint
 * @typicalname uiPaint
 * @version 15.5.22
 */
'use strict'

import ThePaint from './ThePaint'
import ThePaintStyle from './ThePaintStyle'

export {
  ThePaint,
  ThePaintStyle,
}

export default {
  ThePaint,
  ThePaintStyle,
}
