// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Hand write painting
 * @module @the-/ui-paint
 * @typicalname uiPaint
 * @version 17.0.9
 */
'use strict'

import ThePaint from './ThePaint'

export {
  ThePaint,
}
