// Code generated by coz. DO NOT EDIT.
/**
 * Hand write painting
 * @module @the-/ui-paint
 */
'use strict'

import ThePaint from './ThePaint'
import ThePaintStyle from './ThePaintStyle'

export {
  ThePaint,
  ThePaintStyle,
}

export default {
      ThePaint,
      ThePaintStyle,
}
