// Code generated by coz. DO NOT EDIT.
/**
 * Constants for the-components
 * @module @the-/const-ui
 */
'use strict'

const SupportedProps_ = require('./SupportedProps')
const ThemeValues_ = require('./ThemeValues')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.SupportedProps = SupportedProps_
exports.ThemeValues = ThemeValues_

module.exports = {
  SupportedProps: SupportedProps_,
  ThemeValues: ThemeValues_,
}
