// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/const-ui
 * @version 15.4.0
 * @description Constants for the-components
 * @typicalname constUi
 * @license MIT
 */
'use strict'

const SupportedProps_ = require('./SupportedProps')
const ThemeValues_ = require('./ThemeValues')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.SupportedProps = SupportedProps_
exports.ThemeValues = ThemeValues_

module.exports = {
  SupportedProps: SupportedProps_,
  ThemeValues: ThemeValues_,
}
