// Code generated by coz. DO NOT EDIT.
/**
 * @description Pager of the-components
 * @module @the-/ui-pager
 * @typicalname uiPager
 * @version 15.4.8
 */
'use strict'

import ThePager from './ThePager'
import ThePagerStyle from './ThePagerStyle'

export {
  ThePager,
  ThePagerStyle,
}

export default {
  ThePager,
  ThePagerStyle,
}
