// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Pager of the-components
 * @module @the-/ui-pager
 * @typicalname uiPager
 * @version 16.0.0
 */
'use strict'

import ThePager from './ThePager'

export {
  ThePager,
}
