// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Hash object to hold key-value pairs
 * @license MIT
 * @module @the-/hash
 * @typicalname hash
 * @version 15.4.9
 */
'use strict'

const TheHash_ = require('./TheHash')
const create_ = require('./create')
const proxy_ = require('./proxy')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheHash = TheHash_
exports.create = create_
exports.proxy = proxy_

module.exports = default__
