// Code generated by coz. DO NOT EDIT.
/**
 * Base of the streams
 * @module @the-/stream
 */
'use strict'

const Consumer_ = require('./Consumer')
const Provider_ = require('./Provider')
const TheStream_ = require('./TheStream')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Consumer = Consumer_
exports.Provider = Provider_
exports.TheStream = TheStream_

module.exports = {
  Consumer: Consumer_,
  Provider: Provider_,
  TheStream: TheStream_,
}
