// Code generated by coz. DO NOT EDIT.
/**
 * @description Base of the streams
 * @license MIT
 * @module @the-/stream
 * @typicalname stream
 * @version 15.4.7
 */
'use strict'

const Consumer_ = require('./Consumer')
const Provider_ = require('./Provider')
const TheStream_ = require('./TheStream')
const helpers_ = require('./helpers')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Consumer = Consumer_
exports.Provider = Provider_
exports.TheStream = TheStream_
exports.helpers = helpers_

module.exports = {
  Consumer: Consumer_,
  Provider: Provider_,
  TheStream: TheStream_,
  helpers: helpers_,
}
