// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-view
 * @typicalname uiView
 * @version 15.4.5
 * @description View of the-components
 */
'use strict'

import TheView from './TheView'
import TheViewStyle from './TheViewStyle'

export {
  TheView,
  TheViewStyle,
}

export default {
  TheView,
  TheViewStyle,
}
