// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description View of the-components
 * @module @the-/ui-view
 * @typicalname uiView
 * @version 15.4.9
 */
'use strict'

import TheView from './TheView'
import TheViewStyle from './TheViewStyle'

export {
  TheView,
  TheViewStyle,
}

export default {
  TheView,
  TheViewStyle,
}
