// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description View of the-components
 * @module @the-/ui-view
 * @typicalname uiView
 * @version 16.0.1
 */
'use strict'

import TheView from './TheView'

export {
  TheView,
}
