// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Router of the-components
 * @module @the-/ui-router
 * @typicalname uiRouter
 * @version 15.4.8
 */
'use strict'

import TheRouter from './TheRouter'
import TheRouterStyle from './TheRouterStyle'

export {
  TheRouter,
  TheRouterStyle,
}

export default {
  TheRouter,
  TheRouterStyle,
}
