// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck
/**
 * @description Router of the-components
 * @module @the-/ui-router
 * @typicalname uiRouter
 * @version 16.0.1
 */
'use strict'

import TheRouter from './TheRouter'

export {
  TheRouter,
}
