// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Footer of the-components
 * @module @the-/ui-footer
 * @typicalname uiFooter
 * @version 15.4.16
 */
'use strict'

import TheFooter from './TheFooter'
import TheFooterStyle from './TheFooterStyle'

export {
  TheFooter,
  TheFooterStyle,
}
