// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Footer of the-components
 * @module @the-/ui-footer
 * @typicalname uiFooter
 * @version 16.0.0
 */
'use strict'

import TheFooter from './TheFooter'

export {
  TheFooter,
}
