// Code generated by coz. DO NOT EDIT.
/**
 * Footer of the-components
 * @module @the-/ui-footer
 */
'use strict'

import TheFooter from './TheFooter'
import TheFooterStyle from './TheFooterStyle'

export {
  TheFooter,
  TheFooterStyle,
}

export default {
  TheFooter,
  TheFooterStyle,
}
