// Code generated by coz. DO NOT EDIT.
/**
 * View components
 * @module views
 */
'use strict'

import ErrorNotfoundView from './error/ErrorNotfoundView'
import HomeView from './HomeView'

export {
 ErrorNotfoundView,
 HomeView,
}
