// Code generated by coz. DO NOT EDIT.
/**
 * View components with lazy loading
 * @module views
 */
'use strict'

import React from 'react'

export const ErrorNotfoundView = React.lazy(() => import('./error/ErrorNotfoundView'))
export const HomeView = React.lazy(() => import('./HomeView'))
