// Code generated by coz. DO NOT EDIT.
/**
 * @description View components with lazy loading
 * @memberof module:client.ui.views
 * @namespace views
 */
'use strict'

import React from 'react'

export const ErrorNotfoundView = React.lazy(() => import('./error/ErrorNotfoundView'))
export const HomeView = React.lazy(() => import('./HomeView'))
