// Code generated by coz. DO NOT EDIT.
/**
 * Root element of the-components
 * @module @the-/root
 */
'use strict'

import TheRoot from './TheRoot'
import TheRootStyle from './TheRootStyle'

export {
  TheRoot,
  TheRootStyle,
}

export default {
      TheRoot,
      TheRootStyle,
}
