// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/polyfill
 * @version 15.4.0
 * @description Polyfill of the-frameworks
 * @typicalname polyfill
 * @license MIT
 */
'use strict'

const ThePolyfill_ = require('./ThePolyfill')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ThePolyfill = ThePolyfill_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
