// Code generated by coz. DO NOT EDIT.
/**
 * JS support version checker
 * @module the-support
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const TheSupport_ = require('./TheSupport')
const create_ = require('./create')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSupport = _d(TheSupport_)
exports.create = _d(create_)

module.exports = {
  TheSupport: _d(TheSupport_),
  create: _d(create_),
}
