// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description JS support version checker
 * @license MIT
 * @module @the-/support
 * @typicalname support
 * @version 15.4.17
 */
'use strict'

const TheSupport_ = require('./TheSupport')
const create_ = require('./create')
const helpers_ = require('./helpers')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSupport = TheSupport_
exports.create = create_
exports.helpers = helpers_

module.exports = {
  TheSupport: TheSupport_,
  create: create_,
  helpers: helpers_,
}
