// Code generated by coz. DO NOT EDIT.
/**
 * JS support version checker
 * @module @the-/support
 */
'use strict'

const TheSupport_ = require('./TheSupport')
const create_ = require('./create')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSupport = TheSupport_
exports.create = create_

module.exports = {
  TheSupport: TheSupport_,
  create: create_,
}
