// Code generated by coz. DO NOT EDIT.
/**
 * Db resource classes
 * @module resources
 */
'use strict'

const RoomResource_ = require('./RoomResource')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.RoomResource = RoomResource_

module.exports = {
  RoomResource: RoomResource_,
}
