// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description QRCode the-component
 * @module @the-/ui-qr
 * @typicalname uiQr
 * @version 16.0.0
 */
'use strict'

import TheQr from './TheQr'

export {
  TheQr,
}
