// Code generated by coz. DO NOT EDIT.
/**
 * QRCode the-component
 * @module @the-/ui-qr
 */
'use strict'

import TheQr from './TheQr'
import TheQrStyle from './TheQrStyle'

export {
  TheQr,
  TheQrStyle,
}

export default {
      TheQr,
      TheQrStyle,
}
