// Code generated by coz. DO NOT EDIT.
/**
 * @description QRCode the-component
 * @module @the-/ui-qr
 * @typicalname uiQr
 * @version 15.4.8
 */
'use strict'

import TheQr from './TheQr'
import TheQrStyle from './TheQrStyle'

export {
  TheQr,
  TheQrStyle,
}

export default {
  TheQr,
  TheQrStyle,
}
