// Code generated by coz. DO NOT EDIT.
/**
 * iFrame of the-components
 * @module @the-/frame
 */
'use strict'

import TheFrame from './TheFrame'
import TheFrameStyle from './TheFrameStyle'

export {
  TheFrame,
  TheFrameStyle,
}

export default {
      TheFrame,
      TheFrameStyle,
}
