// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Operation handlers
 * @namespace operation
 */
'use strict'

const createOperationFor_ = require('./createOperationFor')
const destroyOperationFor_ = require('./destroyOperationFor')
const detailOperationFor_ = require('./detailOperationFor')
const editOperationFor_ = require('./editOperationFor')
const listOperationFor_ = require('./listOperationFor')
const operationFor_ = require('./operationFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.createOperationFor = createOperationFor_
exports.destroyOperationFor = destroyOperationFor_
exports.detailOperationFor = detailOperationFor_
exports.editOperationFor = editOperationFor_
exports.listOperationFor = listOperationFor_
exports.operationFor = operationFor_

module.exports = {
  createOperationFor: createOperationFor_,
  destroyOperationFor: destroyOperationFor_,
  detailOperationFor: detailOperationFor_,
  editOperationFor: editOperationFor_,
  listOperationFor: listOperationFor_,
  operationFor: operationFor_,
}
