// Code generated by coz. DO NOT EDIT.
/**
 * @description Operation handlers
 * @namespace operation
 */
'use strict'

const createOperationForFor_ = require('./createOperationForFor')
const destroyOperationForFor_ = require('./destroyOperationForFor')
const detailOperationFor_ = require('./detailOperationFor')
const editOperationForFor_ = require('./editOperationForFor')
const listOperationFor_ = require('./listOperationFor')
const operationForFor_ = require('./operationForFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.createOperationForFor = createOperationForFor_
exports.destroyOperationForFor = destroyOperationForFor_
exports.detailOperationFor = detailOperationFor_
exports.editOperationForFor = editOperationForFor_
exports.listOperationFor = listOperationFor_
exports.operationForFor = operationForFor_

module.exports = {
  createOperationForFor: createOperationForFor_,
  destroyOperationForFor: destroyOperationForFor_,
  detailOperationFor: detailOperationFor_,
  editOperationForFor: editOperationForFor_,
  listOperationFor: listOperationFor_,
  operationForFor: operationForFor_,
}
