// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Route of the-components
 * @module @the-/ui-route
 * @typicalname uiRoute
 * @version 15.4.12
 */
'use strict'

import TheRoute from './TheRoute'
import TheRouteStack from './TheRouteStack'
import TheRouteStyle from './TheRouteStyle'

export {
  TheRoute,
  TheRouteStack,
  TheRouteStyle,
}
