// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Route of the-components
 * @module @the-/ui-route
 * @typicalname uiRoute
 * @version 16.0.1
 */
'use strict'

import TheRoute from './TheRoute'
import TheRouteStack from './TheRouteStack'

export {
  TheRoute,
  TheRouteStack,
}
