// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberof module:@the-/db
 * @namespace mixins
 */
'use strict'

const cascadeMix_ = require('./cascadeMix')
const cliMix_ = require('./cliMix')
const migrateMix_ = require('./migrateMix')
const refreshMix_ = require('./refreshMix')
const resourceMix_ = require('./resourceMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.cascadeMix = cascadeMix_
exports.cliMix = cliMix_
exports.migrateMix = migrateMix_
exports.refreshMix = refreshMix_
exports.resourceMix = resourceMix_

module.exports = {
  cascadeMix: cascadeMix_,
  cliMix: cliMix_,
  migrateMix: migrateMix_,
  refreshMix: refreshMix_,
  resourceMix: resourceMix_,
}
