// Code generated by coz. DO NOT EDIT.
/**
 * Mixins
 * @module mixins
 */
'use strict'

const cascadeMix_ = require('./cascadeMix')
const cliMix_ = require('./cliMix')
const exportImportMix_ = require('./exportImportMix')
const migrateMix_ = require('./migrateMix')
const refreshMix_ = require('./refreshMix')
const resourceMix_ = require('./resourceMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.cascadeMix = cascadeMix_
exports.cliMix = cliMix_
exports.exportImportMix = exportImportMix_
exports.migrateMix = migrateMix_
exports.refreshMix = refreshMix_
exports.resourceMix = resourceMix_

module.exports = {
  cascadeMix: cascadeMix_,
  cliMix: cliMix_,
  exportImportMix: exportImportMix_,
  migrateMix: migrateMix_,
  refreshMix: refreshMix_,
  resourceMix: resourceMix_,
}
