// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Check utility for the-framework
 * @license MIT
 * @module @the-/check-env
 * @typicalname checkEnv
 * @version 15.6.0
 */
'use strict'

const isProduction_ = require('./isProduction')
const unlessProduction_ = require('./unlessProduction')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.isProduction = isProduction_
exports.unlessProduction = unlessProduction_

module.exports = {
  isProduction: isProduction_,
  unlessProduction: unlessProduction_,
}
