// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Touch event handler
 * @module @the-/ui-touchable
 * @typicalname uiTouchable
 * @version 15.5.1
 */
'use strict'

import TheTouchable from './TheTouchable'

export {
  TheTouchable,
}
