// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Main for the-components
 * @module @the-/ui-main
 * @typicalname uiMain
 * @version 16.0.0
 */
'use strict'

import TheMain from './TheMain'

export {
  TheMain,
}
