// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Main for the-components
 * @module @the-/ui-main
 * @typicalname uiMain
 * @version 15.4.12
 */
'use strict'

import TheMain from './TheMain'
import TheMainStyle from './TheMainStyle'

export {
  TheMain,
  TheMainStyle,
}

export default {
  TheMain,
  TheMainStyle,
}
