// Code generated by coz. DO NOT EDIT.
/**
 * Main for the-components
 * @module the-main
 */
'use strict'

import TheMain from './TheMain'
import TheMainStyle from './TheMainStyle'

export {
 TheMain,
 TheMainStyle,
}
