// Code generated by coz. DO NOT EDIT.
/**
 * Project configurations
 * @module conf
 */
'use strict'

const GlobalKeys_ = require('./GlobalKeys')
const Icons_ = require('./Icons')
const SrcSets_ = require('./SrcSets')
const Styles_ = require('./Styles')
const UI_ = require('./UI')
const Urls_ = require('./Urls')
const locales_ = require('./locales')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.GlobalKeys = GlobalKeys_
exports.Icons = Icons_
exports.SrcSets = SrcSets_
exports.Styles = Styles_
exports.UI = UI_
exports.Urls = Urls_
exports.locales = locales_

module.exports = {
  GlobalKeys: GlobalKeys_,
  Icons: Icons_,
  SrcSets: SrcSets_,
  Styles: Styles_,
  UI: UI_,
  Urls: Urls_,
  locales: locales_,
}
