// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/state
 * @namespace helpers
 */
'use strict'

const reduxHelper_ = require('./reduxHelper')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.reduxHelper = reduxHelper_

module.exports = {
  reduxHelper: reduxHelper_,
}
