// Code generated by coz. DO NOT EDIT.
/**
 * Cache manager of the-frameworks
 * @module @the-/cache
 */
'use strict'

const TheCache_ = require('./TheCache')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheCache = TheCache_
exports.create = create_

module.exports = default__
