// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/metrics-presets
 * @version 15.4.2
 * @description Preset of the-metrics
 * @typicalname metricsPresets
 * @license MIT
 */
'use strict'

const RenderingCountMetrics_ = require('./RenderingCountMetrics')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.RenderingCountMetrics = RenderingCountMetrics_

module.exports = {
  RenderingCountMetrics: RenderingCountMetrics_,
}
