/**
 * eslintignore
 * @memberOf module:@the-/templates
 * @function eslintignore
 * @param {Object} config
 * @returns {Object}
 */
'use strict'

const { spawnSync } = require('child_process')
const _tmpl = require('./_tmpl')

/** @lends module:@the-/templates.eslintignore */
function eslintignore(paths = []) {
  const { stdout } = spawnSync('git', [
    'grep',
    '--name-only',
    'Code generated by coz. DO NOT EDIT.',
    '*.js',
    '*.jsx',
  ])
  const cozFiles = stdout
    ? stdout
        .toString()
        .split('\n')
        .filter(Boolean)
        .map((path) => `/${path}`)
    : []
  return {
    data: {
      cozFiles,
      paths,
    },
    force: true,
    mode: '444',
    path: `.eslintignore`,
    tmpl: _tmpl('eslintignore.hbs'),
  }
}

module.exports = eslintignore
