// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/templates
 * @version 15.4.9
 * @description Templates for the-projects
 * @typicalname templates
 * @license MIT
 */
'use strict'

const Ctrl_ = require('./Ctrl')
const Dialogs_ = require('./Dialogs')
const Hook_ = require('./Hook')
const License_ = require('./License')
const Readme_ = require('./Readme')
const Resources_ = require('./Resources')
const Scene_ = require('./Scene')
const Stateful_ = require('./Stateful')
const Stateless_ = require('./Stateless')
const Stream_ = require('./Stream')
const View_ = require('./View')
const bin_ = require('./bin')
const dir_ = require('./dir')
const errorPage_ = require('./errorPage')
const eslintignore_ = require('./eslintignore')
const eslintrc_ = require('./eslintrc')
const mapping_ = require('./mapping')
const nginx_ = require('./nginx')
const pcssVars_ = require('./pcssVars')
const prettierrc_ = require('./prettierrc')
const scopes_ = require('./scopes')
const test_ = require('./test')
const vhost_ = require('./vhost')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Ctrl = Ctrl_
exports.Dialogs = Dialogs_
exports.Hook = Hook_
exports.License = License_
exports.Readme = Readme_
exports.Resources = Resources_
exports.Scene = Scene_
exports.Stateful = Stateful_
exports.Stateless = Stateless_
exports.Stream = Stream_
exports.View = View_
exports.bin = bin_
exports.dir = dir_
exports.errorPage = errorPage_
exports.eslintignore = eslintignore_
exports.eslintrc = eslintrc_
exports.mapping = mapping_
exports.nginx = nginx_
exports.pcssVars = pcssVars_
exports.prettierrc = prettierrc_
exports.scopes = scopes_
exports.test = test_
exports.vhost = vhost_

module.exports = {
  Ctrl: Ctrl_,
  Dialogs: Dialogs_,
  Hook: Hook_,
  License: License_,
  Readme: Readme_,
  Resources: Resources_,
  Scene: Scene_,
  Stateful: Stateful_,
  Stateless: Stateless_,
  Stream: Stream_,
  View: View_,
  bin: bin_,
  dir: dir_,
  errorPage: errorPage_,
  eslintignore: eslintignore_,
  eslintrc: eslintrc_,
  mapping: mapping_,
  nginx: nginx_,
  pcssVars: pcssVars_,
  prettierrc: prettierrc_,
  scopes: scopes_,
  test: test_,
  vhost: vhost_,
}
