// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Root element of the-components
 * @module @the-/ui-root
 * @typicalname uiRoot
 * @version 15.4.13
 */
'use strict'

import TheRoot from './TheRoot'
import TheRootStyle from './TheRootStyle'

export {
  TheRoot,
  TheRootStyle,
}

export default {
  TheRoot,
  TheRootStyle,
}
