// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Root element of the-components
 * @module @the-/ui-root
 * @typicalname uiRoot
 * @version 16.0.0
 */
'use strict'

import TheRoot from './TheRoot'

export {
  TheRoot,
}
