// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Adapter functions
 * @memberOf module:@the-/server
 * @namespace adapters
 */
'use strict'

const redisAdapter_ = require('./redisAdapter')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.redisAdapter = redisAdapter_

module.exports = {
  redisAdapter: redisAdapter_,
}
