// Code generated by coz. DO NOT EDIT.
/**
 * Pager of the-components
 * @module the-pager
 */
'use strict'

import ThePager from './ThePager'
import ThePagerStyle from './ThePagerStyle'

export {
 ThePager,
 ThePagerStyle,
}
