// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/mixin-scene
 * @namespace helpers
 */
'use strict'

const asClassMixin_ = require('./asClassMixin')
const asMethodWrap_ = require('./asMethodWrap')
const injectProperties_ = require('./injectProperties')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.asClassMixin = asClassMixin_
exports.asMethodWrap = asMethodWrap_
exports.injectProperties = injectProperties_

module.exports = {
  asClassMixin: asClassMixin_,
  asMethodWrap: asMethodWrap_,
  injectProperties: injectProperties_,
}
