// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module helpers
 */
'use strict'

const logger_ = require('./logger')
const serializer_ = require('./serializer')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.logger = logger_
exports.serializer = serializer_

module.exports = {
  logger: logger_,
  serializer: serializer_,
}
