// Code generated by coz. DO NOT EDIT.
/**
 * @description Utility for the-components
 * @license MIT
 * @module @the-/util-ui
 * @typicalname utilUi
 * @version 15.4.8
 */
'use strict'

const asHOC_ = require('./asHOC')
const asStyleData_ = require('./asStyleData')
const changedProps_ = require('./changedProps')
const colorAlpha_ = require('./colorAlpha')
const eventHandlersFor_ = require('./eventHandlersFor')
const htmlAttributesFor_ = require('./htmlAttributesFor')
const isKeyCode_ = require('./isKeyCode')
const isServerSide_ = require('./isServerSide')
const isVideoSrc_ = require('./isVideoSrc')
const newId_ = require('./newId')
const readFileAsDataURL_ = require('./readFileAsDataURL')
const toggleBodyClass_ = require('./toggleBodyClass')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.asHOC = asHOC_
exports.asStyleData = asStyleData_
exports.changedProps = changedProps_
exports.colorAlpha = colorAlpha_
exports.eventHandlersFor = eventHandlersFor_
exports.htmlAttributesFor = htmlAttributesFor_
exports.isKeyCode = isKeyCode_
exports.isServerSide = isServerSide_
exports.isVideoSrc = isVideoSrc_
exports.newId = newId_
exports.readFileAsDataURL = readFileAsDataURL_
exports.toggleBodyClass = toggleBodyClass_

module.exports = {
  asHOC: asHOC_,
  asStyleData: asStyleData_,
  changedProps: changedProps_,
  colorAlpha: colorAlpha_,
  eventHandlersFor: eventHandlersFor_,
  htmlAttributesFor: htmlAttributesFor_,
  isKeyCode: isKeyCode_,
  isServerSide: isServerSide_,
  isVideoSrc: isVideoSrc_,
  newId: newId_,
  readFileAsDataURL: readFileAsDataURL_,
  toggleBodyClass: toggleBodyClass_,
}
