// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Utility for the-components
 * @license MIT
 * @module @the-/util-ui
 * @typicalname utilUi
 * @version 16.1.0
 */
'use strict'

const asStyleData_ = require('./asStyleData')
const base64ToBlob_ = require('./base64ToBlob')
const changedProps_ = require('./changedProps')
const eventHandlersFor_ = require('./eventHandlersFor')
const htmlAttributesFor_ = require('./htmlAttributesFor')
const isKeyCode_ = require('./isKeyCode')
const isServerSide_ = require('./isServerSide')
const isVideoSrc_ = require('./isVideoSrc')
const newId_ = require('./newId')
const readFileAsDataURL_ = require('./readFileAsDataURL')
const scrollToElement_ = require('./scrollToElement')
const stopTouchScrolling_ = require('./stopTouchScrolling')
const toggleBodyClass_ = require('./toggleBodyClass')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.asStyleData = asStyleData_
exports.base64ToBlob = base64ToBlob_
exports.changedProps = changedProps_
exports.eventHandlersFor = eventHandlersFor_
exports.htmlAttributesFor = htmlAttributesFor_
exports.isKeyCode = isKeyCode_
exports.isServerSide = isServerSide_
exports.isVideoSrc = isVideoSrc_
exports.newId = newId_
exports.readFileAsDataURL = readFileAsDataURL_
exports.scrollToElement = scrollToElement_
exports.stopTouchScrolling = stopTouchScrolling_
exports.toggleBodyClass = toggleBodyClass_

module.exports = {
  asStyleData: asStyleData_,
  base64ToBlob: base64ToBlob_,
  changedProps: changedProps_,
  eventHandlersFor: eventHandlersFor_,
  htmlAttributesFor: htmlAttributesFor_,
  isKeyCode: isKeyCode_,
  isServerSide: isServerSide_,
  isVideoSrc: isVideoSrc_,
  newId: newId_,
  readFileAsDataURL: readFileAsDataURL_,
  scrollToElement: scrollToElement_,
  stopTouchScrolling: stopTouchScrolling_,
  toggleBodyClass: toggleBodyClass_,
}
