// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description State holder for the-components
 * @license MIT
 * @module @the-/state
 * @typicalname state
 * @version 15.4.9
 */
'use strict'

const TheState_ = require('./TheState')
const constants_ = require('./constants')
const create_ = require('./create')
const helpers_ = require('./helpers')
const state_ = require('./state')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheState = TheState_
exports.constants = constants_
exports.create = create_
exports.helpers = helpers_
exports.state = state_

module.exports = default__
