// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/state
 * @version 15.4.0
 * @description State holder for the-components
 * @typicalname state
 * @license MIT
 */
'use strict'

const TheState_ = require('./TheState')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheState = TheState_
exports.create = create_

module.exports = default__
