// Code generated by coz. DO NOT EDIT.
/**
 * Footer of the-components
 * @module the-footer
 */
'use strict'

import TheFooter from './TheFooter'
import TheFooterStyle from './TheFooterStyle'

export {
 TheFooter,
 TheFooterStyle,
}
