// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-cycle
 * @typicalname uiCycle
 * @version 15.4.5
 * @description Component with life cycle
 */
'use strict'

import TheCycle from './TheCycle'

export {
  TheCycle,
}

export default {
  TheCycle,
}
