// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Component with life cycle
 * @module @the-/ui-cycle
 * @typicalname uiCycle
 * @version 15.4.12
 */
'use strict'

import TheCycle from './TheCycle'

export {
  TheCycle,
}
