// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Steps for the-components
 * @module @the-/ui-step
 * @typicalname uiStep
 * @version 15.4.16
 */
'use strict'

import TheStep from './TheStep'
import TheStepBar from './TheStepBar'
import TheStepStyle from './TheStepStyle'

export {
  TheStep,
  TheStepBar,
  TheStepStyle,
}
