// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Steps for the-components
 * @module @the-/ui-step
 * @typicalname uiStep
 * @version 16.0.1
 */
'use strict'

import TheStep from './TheStep'
import TheStepBar from './TheStepBar'

export {
  TheStep,
  TheStepBar,
}
