// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description File utility for the-framework
 * @license MIT
 * @module @the-/util-file
 * @typicalname utilFile
 * @version 15.7.4
 */
'use strict'

const copyAsJsonSync_ = require('./copyAsJsonSync')
const delSync_ = require('./delSync')
const fileSizeOf_ = require('./fileSizeOf')
const fileTypeOf_ = require('./fileTypeOf')
const isJSON5File_ = require('./isJSON5File')
const readAsJson_ = require('./readAsJson')
const readAsJsonSync_ = require('./readAsJsonSync')
const readAsYaml_ = require('./readAsYaml')
const statSync_ = require('./statSync')
const writeAsJson_ = require('./writeAsJson')
const writeAsJsonSync_ = require('./writeAsJsonSync')
const writeAsYaml_ = require('./writeAsYaml')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.copyAsJsonSync = copyAsJsonSync_
exports.delSync = delSync_
exports.fileSizeOf = fileSizeOf_
exports.fileTypeOf = fileTypeOf_
exports.isJSON5File = isJSON5File_
exports.readAsJson = readAsJson_
exports.readAsJsonSync = readAsJsonSync_
exports.readAsYaml = readAsYaml_
exports.statSync = statSync_
exports.writeAsJson = writeAsJson_
exports.writeAsJsonSync = writeAsJsonSync_
exports.writeAsYaml = writeAsYaml_

module.exports = {
  copyAsJsonSync: copyAsJsonSync_,
  delSync: delSync_,
  fileSizeOf: fileSizeOf_,
  fileTypeOf: fileTypeOf_,
  isJSON5File: isJSON5File_,
  readAsJson: readAsJson_,
  readAsJsonSync: readAsJsonSync_,
  readAsYaml: readAsYaml_,
  statSync: statSync_,
  writeAsJson: writeAsJson_,
  writeAsJsonSync: writeAsJsonSync_,
  writeAsYaml: writeAsYaml_,
}
