// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/rtc-client
 * @version 15.4.0
 * @description Client for the-rtc
 * @typicalname rtcClient
 * @license MIT
 */
'use strict'

const TheRTCClient_ = require('./TheRTCClient')
const constants_ = require('./constants')
const create_ = require('./create')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRTCClient = TheRTCClient_
exports.constants = constants_
exports.create = create_
exports.mixins = mixins_

module.exports = default__
