// Code generated by coz. DO NOT EDIT.
/**
 * @description Dynamic meta attribute injector for the-components
 * @module @the-/ui-meta
 * @typicalname uiMeta
 * @version 15.4.5
 */
'use strict'

import TheMeta from './TheMeta'

export {
  TheMeta,
}

export default {
  TheMeta,
}
