// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Modeling functions
 * @memberOf module:@the-/driver-sequelize
 * @namespace modeling
 */
'use strict'

const defineModel_ = require('./defineModel')
const defineModelColumn_ = require('./defineModelColumn')
const defineModelIndexes_ = require('./defineModelIndexes')
const prepareModel_ = require('./prepareModel')
const prepareModelAssociations_ = require('./prepareModelAssociations')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.defineModel = defineModel_
exports.defineModelColumn = defineModelColumn_
exports.defineModelIndexes = defineModelIndexes_
exports.prepareModel = prepareModel_
exports.prepareModelAssociations = prepareModelAssociations_

module.exports = {
  defineModel: defineModel_,
  defineModelColumn: defineModelColumn_,
  defineModelIndexes: defineModelIndexes_,
  prepareModel: prepareModel_,
  prepareModelAssociations: prepareModelAssociations_,
}
