// Code generated by coz. DO NOT EDIT.
/**
 * Demo of the-components
 * @module @the-/demo-component
 */
'use strict'

import TheDemoComponent from './TheDemoComponent'
import TheDemoComponentStyle from './TheDemoComponentStyle'

export {
  TheDemoComponent,
  TheDemoComponentStyle,
}

export default {
      TheDemoComponent,
      TheDemoComponentStyle,
}
