// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/client
 * @namespace helpers
 */
'use strict'

const asController_ = require('./asController')
const debugController_ = require('./debugController')
const debugStream_ = require('./debugStream')
const parseClientUrl_ = require('./parseClientUrl')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.asController = asController_
exports.debugController = debugController_
exports.debugStream = debugStream_
exports.parseClientUrl = parseClientUrl_

module.exports = {
  asController: asController_,
  debugController: debugController_,
  debugStream: debugStream_,
  parseClientUrl: parseClientUrl_,
}
