// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/client
 * @namespace helpers
 */
'use strict'

const InfoAccess_ = require('./InfoAccess')
const PingSender_ = require('./PingSender')
const RemoteStream_ = require('./RemoteStream')
const asController_ = require('./asController')
const debugController_ = require('./debugController')
const debugStream_ = require('./debugStream')
const logger_ = require('./logger')
const parseClientUrl_ = require('./parseClientUrl')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.InfoAccess = InfoAccess_
exports.PingSender = PingSender_
exports.RemoteStream = RemoteStream_
exports.asController = asController_
exports.debugController = debugController_
exports.debugStream = debugStream_
exports.logger = logger_
exports.parseClientUrl = parseClientUrl_

module.exports = {
  InfoAccess: InfoAccess_,
  PingSender: PingSender_,
  RemoteStream: RemoteStream_,
  asController: asController_,
  debugController: debugController_,
  debugStream: debugStream_,
  logger: logger_,
  parseClientUrl: parseClientUrl_,
}
