// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Scope classes
 * @memberOf module:@the-/scope
 * @namespace scopes
 */
'use strict'

const ArrayScope_ = require('./ArrayScope')
const BooleanScope_ = require('./BooleanScope')
const NullScope_ = require('./NullScope')
const NumberScope_ = require('./NumberScope')
const ObjectScope_ = require('./ObjectScope')
const Scope_ = require('./Scope')
const ScopeScope_ = require('./ScopeScope')
const StringScope_ = require('./StringScope')
const ValueScope_ = require('./ValueScope')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ArrayScope = ArrayScope_
exports.BooleanScope = BooleanScope_
exports.NullScope = NullScope_
exports.NumberScope = NumberScope_
exports.ObjectScope = ObjectScope_
exports.Scope = Scope_
exports.ScopeScope = ScopeScope_
exports.StringScope = StringScope_
exports.ValueScope = ValueScope_

module.exports = {
  ArrayScope: ArrayScope_,
  BooleanScope: BooleanScope_,
  NullScope: NullScope_,
  NumberScope: NumberScope_,
  ObjectScope: ObjectScope_,
  Scope: Scope_,
  ScopeScope: ScopeScope_,
  StringScope: StringScope_,
  ValueScope: ValueScope_,
}
