// Code generated by coz. DO NOT EDIT.
/**
 * Module mappings
 * @module mappings
 */
'use strict'

const SceneMapping_ = require('./SceneMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.SceneMapping = SceneMapping_

module.exports = {
  SceneMapping: SceneMapping_,
}
