// Code generated by coz. DO NOT EDIT.
/**
 * Scene mapping
 * @memberof mappings
 * @namespace SceneMapping
 */
'use strict'

const sc = require('../scenes')

module.exports =
  /** mappings.SceneMapping */
  {
    appScene: sc.AppScene,
    connectionRetryScene: sc.ConnectionRetryScene,
    homeScene: sc.HomeScene,
    toastScene: sc.ToastScene,
  }

Object.freeze(module.exports)
