// Code generated by coz. DO NOT EDIT.
/**
 * Scene mapping
 * @namespace SceneMapping
 */
'use strict'

const sc = require('../scenes')

module.exports = Object.freeze({
  'appScene': sc.AppScene,
  'connectionRetryScene': sc.ConnectionRetryScene,
  'homeScene': sc.HomeScene,
  'toastScene': sc.ToastScene,
})
