// Code generated by coz. DO NOT EDIT.
/**
 * Button of the-components
 * @module the-button
 */
'use strict'

import TheButton from './TheButton'
import TheButtonGroup from './TheButtonGroup'
import TheButtonStyle from './TheButtonStyle'

export {
 TheButton,
 TheButtonGroup,
 TheButtonStyle,
}
