// Code generated by coz. DO NOT EDIT.
/**
 * @description Mail client for the-framework
 * @license MIT
 * @module @the-/mail
 * @typicalname mail
 * @version 15.4.8
 */
'use strict'

const TheMail_ = require('./TheMail')
const create_ = require('./create')
const helpers_ = require('./helpers')
const sending_ = require('./sending')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheMail = TheMail_
exports.create = create_
exports.helpers = helpers_
exports.sending = sending_

module.exports = default__
