// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-form
 * @typicalname uiForm
 * @version 15.4.5
 * @description Form of the-components
 */
'use strict'

import TheForm from './TheForm'
import TheFormBinder from './TheFormBinder'
import TheFormStyle from './TheFormStyle'

export {
  TheForm,
  TheFormBinder,
  TheFormStyle,
}

export default {
  TheForm,
  TheFormBinder,
  TheFormStyle,
}
