// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/resource
 * @version 15.4.1
 * @description Base of the-resource
 * @typicalname resource
 * @license MIT
 */
'use strict'

const DataTypes_ = require('./DataTypes')
const TheResource_ = require('./TheResource')
const create_ = require('./create')
const isResourceClass_ = require('./isResourceClass')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.DataTypes = DataTypes_
exports.TheResource = TheResource_
exports.create = create_
exports.isResourceClass = isResourceClass_
exports.mixins = mixins_

module.exports = default__
