// Code generated by coz. DO NOT EDIT.
/**
 * Controller mapping
 * @memberof mappings
 * @namespace ControllerMapping
 */
'use strict'

const c = require('../controllers')

module.exports = Object.freeze(
  /** mappings.ControllerMapping */
  {
    appCtrl: c.AppCtrl,
  }
)
