// Code generated by coz. DO NOT EDIT.
/**
 * Controller mapping
 * @namespace ControllerMapping
 */
'use strict'

const c = require('../controllers')

module.exports = Object.freeze({
  'appCtrl': c.AppCtrl,
})
