// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * Controller mapping
 * @memberof mappings
 * @namespace ControllerMapping
 */
'use strict'

const c = require('../controllers')

module.exports =
  /** mappings.ControllerMapping */
  {
    appCtrl: c.AppCtrl,
  }

Object.freeze(module.exports)
