// Code generated by coz. DO NOT EDIT.
/**
 * Module mappings
 * @module mappings
 */
'use strict'

const ControllerMapping_ = require('./ControllerMapping')
const ResourceMapping_ = require('./ResourceMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ControllerMapping = ControllerMapping_
exports.ResourceMapping = ResourceMapping_

module.exports = {
  ControllerMapping: ControllerMapping_,
  ResourceMapping: ResourceMapping_,
}
