// Code generated by coz. DO NOT EDIT.
/**
 * Resource mapping
 * @memberof mappings
 * @namespace ResourceMapping
 */
'use strict'

const r = require('../db/resources')

module.exports =
  /** mappings.ResourceMapping */
  {
    Room: r.RoomResource,
  }

Object.freeze(module.exports)
