// Code generated by coz. DO NOT EDIT.
/**
 * Resource mapping
 * @memberof mappings
 * @namespace ResourceMapping
 */
'use strict'

const r = require('../db/resources')

module.exports = Object.freeze(
  /** mappings.ResourceMapping */
  {
    Room: r.RoomResource,
  }
)
