// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-style
 * @version 15.4.2
 * @description Utility for style
 * @typicalname utilStyle
 * @license MIT
 */
'use strict'

const styleString_ = require('./styleString')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.styleString = styleString_

module.exports = {
  styleString: styleString_,
}
