// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Mixin functions
 * @memberOf module:@the-/server
 * @namespace mixins
 */
'use strict'

const clientMix_ = require('./clientMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.clientMix = clientMix_

module.exports = {
  clientMix: clientMix_,
}
