// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberOf module:@the-/server
 * @namespace mixins
 */
'use strict'

const clientMix_ = require('./clientMix')
const infoMix_ = require('./infoMix')
const keepMix_ = require('./keepMix')
const metricsMix_ = require('./metricsMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.clientMix = clientMix_
exports.infoMix = infoMix_
exports.keepMix = keepMix_
exports.metricsMix = metricsMix_

module.exports = {
  clientMix: clientMix_,
  infoMix: infoMix_,
  keepMix: keepMix_,
  metricsMix: metricsMix_,
}
