// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberOf module:@the-/server
 * @namespace mixins
 */
'use strict'

const clientMix_ = require('./clientMix')
const keepMix_ = require('./keepMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.clientMix = clientMix_
exports.keepMix = keepMix_

module.exports = {
  clientMix: clientMix_,
  keepMix: keepMix_,
}
