// Code generated by coz. DO NOT EDIT.
/**
 * Section of the-components
 * @module @the-/ui-section
 */
'use strict'

import TheAccordionSection from './TheAccordionSection'
import TheSection from './TheSection'
import TheSectionStyle from './TheSectionStyle'

export {
  TheAccordionSection,
  TheSection,
  TheSectionStyle,
}

export default {
      TheAccordionSection,
      TheSection,
      TheSectionStyle,
}
