// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Section of the-components
 * @module @the-/ui-section
 * @typicalname uiSection
 * @version 15.4.18
 */
'use strict'

import TheAccordionSection from './TheAccordionSection'
import TheSection from './TheSection'
import TheSectionStyle from './TheSectionStyle'

export {
  TheAccordionSection,
  TheSection,
  TheSectionStyle,
}

export default {
  TheAccordionSection,
  TheSection,
  TheSectionStyle,
}
