// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Section of the-components
 * @module @the-/ui-section
 * @typicalname uiSection
 * @version 16.0.1
 */
'use strict'

import TheAccordionSection from './TheAccordionSection'
import TheSection from './TheSection'

export {
  TheAccordionSection,
  TheSection,
}
