// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Date ui
 * @module @the-/ui-date
 * @typicalname uiDate
 * @version 17.0.2
 */
'use strict'

import TheDateInput from './TheDateInput'
import helpers from './helpers'

export {
  TheDateInput,
  helpers,
}
