// Code generated by coz. DO NOT EDIT.
/**
 * @access protected
 * @description Processor functions
 * @memberOf module:@the-/code
 * @namespace processors
 */
'use strict'

const processCSSProp_ = require('./processCSSProp')
const processCSSRule_ = require('./processCSSRule')
const processFileEnd_ = require('./processFileEnd')
const processJSBlock_ = require('./processJSBlock')
const processJSClass_ = require('./processJSClass')
const processJSComment_ = require('./processJSComment')
const processJSDoc_ = require('./processJSDoc')
const processJSExport_ = require('./processJSExport')
const processJSFunction_ = require('./processJSFunction')
const processJSImport_ = require('./processJSImport')
const processJSON_ = require('./processJSON')
const processJSObject_ = require('./processJSObject')
const processJSPrettier_ = require('./processJSPrettier')
const processJSRequire_ = require('./processJSRequire')
const processJSStrict_ = require('./processJSStrict')
const processJSSwitch_ = require('./processJSSwitch')
const processJSUnused_ = require('./processJSUnused')
const processJSXAttribute_ = require('./processJSXAttribute')
const processPackageJSON_ = require('./processPackageJSON')
const processYAML_ = require('./processYAML')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.processCSSProp = processCSSProp_
exports.processCSSRule = processCSSRule_
exports.processFileEnd = processFileEnd_
exports.processJSBlock = processJSBlock_
exports.processJSClass = processJSClass_
exports.processJSComment = processJSComment_
exports.processJSDoc = processJSDoc_
exports.processJSExport = processJSExport_
exports.processJSFunction = processJSFunction_
exports.processJSImport = processJSImport_
exports.processJSON = processJSON_
exports.processJSObject = processJSObject_
exports.processJSPrettier = processJSPrettier_
exports.processJSRequire = processJSRequire_
exports.processJSStrict = processJSStrict_
exports.processJSSwitch = processJSSwitch_
exports.processJSUnused = processJSUnused_
exports.processJSXAttribute = processJSXAttribute_
exports.processPackageJSON = processPackageJSON_
exports.processYAML = processYAML_

module.exports = {
  processCSSProp: processCSSProp_,
  processCSSRule: processCSSRule_,
  processFileEnd: processFileEnd_,
  processJSBlock: processJSBlock_,
  processJSClass: processJSClass_,
  processJSComment: processJSComment_,
  processJSDoc: processJSDoc_,
  processJSExport: processJSExport_,
  processJSFunction: processJSFunction_,
  processJSImport: processJSImport_,
  processJSON: processJSON_,
  processJSObject: processJSObject_,
  processJSPrettier: processJSPrettier_,
  processJSRequire: processJSRequire_,
  processJSStrict: processJSStrict_,
  processJSSwitch: processJSSwitch_,
  processJSUnused: processJSUnused_,
  processJSXAttribute: processJSXAttribute_,
  processPackageJSON: processPackageJSON_,
  processYAML: processYAML_,
}
