// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Data generator for the-db
 * @license MIT
 * @module @the-/seed
 * @typicalname seed
 * @version 15.4.9
 */
'use strict'

const TheSeed_ = require('./TheSeed')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSeed = TheSeed_
exports.create = create_

module.exports = default__
