
MYSQL_ROOT_PASSWORD=root
MYSQL_USER=t01
MYSQL_PASSWORD=t01
CONTAINER_NAME=driver_sequelize_mysql
docker rm -f ${CONTAINER_NAME}
docker run --name ${CONTAINER_NAME} \
-p 3306:3306 \
-e MYSQL_USER=${MYSQL_USER} \
-e MYSQL_PASSWORD=${MYSQL_PASSWORD} \
-e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -d mysql:5.7
