// Code generated by coz. DO NOT EDIT.
/**
 * @namespace parsers
 * @memberOf module:@the-/code
 * @access protected
 * @description Parser functions
 */
'use strict'

const parseCSS_ = require('./parseCSS')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.parseCSS = parseCSS_

module.exports = {
  parseCSS: parseCSS_,
}
