// Code generated by coz. DO NOT EDIT.
/**
 * @description Theme style for the-components
 * @module @the-/ui-theme-style
 * @typicalname uiThemeStyle
 * @version 15.4.7
 */
'use strict'

import TheThemeStyle from './TheThemeStyle'

export {
  TheThemeStyle,
}

export default {
  TheThemeStyle,
}
