// Code generated by coz. DO NOT EDIT.
'use strict'

import React from 'react'
import PropTypes from 'prop-types'
import c from 'classnames'
import { styleString } from '@the-/util-style'
import { TheStyle } from '@the-/ui-style'

import { TheAltStyle } from '@the-/ui-alt/styles'
import { TheBarStyle } from '@the-/ui-bar/styles'
import { TheBodyStyle } from '@the-/ui-body/styles'
import { TheButtonStyle } from '@the-/ui-button/styles'
import { TheCaughtStyle } from '@the-/ui-caught/styles'
import { TheConditionStyle } from '@the-/ui-condition/styles'
import { TheContainerStyle } from '@the-/ui-container/styles'
import { TheDialogStyle } from '@the-/ui-dialog/styles'
import { TheFooterStyle } from '@the-/ui-footer/styles'
import { TheFormStyle } from '@the-/ui-form/styles'
import { TheHamburgerStyle } from '@the-/ui-hamburger/styles'
import { TheHeaderStyle } from '@the-/ui-header/styles'
import { TheHtmlStyle } from '@the-/ui-html/styles'
import { TheIconStyle } from '@the-/ui-icon/styles'
import { TheImageStyle } from '@the-/ui-image/styles'
import { TheInfoStyle } from '@the-/ui-info/styles'
import { TheInputStyle } from '@the-/ui-input/styles'
import { TheLinkStyle } from '@the-/ui-link/styles'
import { TheMainStyle } from '@the-/ui-main/styles'
import { TheMenuStyle } from '@the-/ui-menu/styles'
import { ThePagerStyle } from '@the-/ui-pager/styles'
import { TheRootStyle } from '@the-/ui-root/styles'
import { TheRouteStyle } from '@the-/ui-route/styles'
import { TheRouterStyle } from '@the-/ui-router/styles'
import { TheSectionStyle } from '@the-/ui-section/styles'
import { TheSpinStyle } from '@the-/ui-spin/styles'
import { TheStepStyle } from '@the-/ui-step/styles'
import { TheTabStyle } from '@the-/ui-tab/styles'
import { TheTableStyle } from '@the-/ui-table/styles'
import { TheToastStyle } from '@the-/ui-toast/styles'
import { TheVideoStyle } from '@the-/ui-video/styles'
import { TheViewStyle } from '@the-/ui-view/styles'

/** Theme Style of the-components */
const TheThemeStyle = ({ id, className, prefix, options }) => (
  <TheStyle {...{ id, prefix }}
            className={c('the-theme-style', className)}
            styles={TheThemeStyle.data(options)}
  />
)

TheThemeStyle.displayName = 'TheThemeStyle'
TheThemeStyle.propTypes = {
  /** Style options */
  options: PropTypes.object,

  /** Style selector prefix */
  prefix: PropTypes.string
}

TheThemeStyle.defaultProps = {
  options: {},
  prefix: null
}

TheThemeStyle.data = (options) => {
  return Object.assign({},
    ...[
      TheAltStyle,
      TheBarStyle,
      TheBodyStyle,
      TheButtonStyle,
      TheCaughtStyle,
      TheConditionStyle,
      TheContainerStyle,
      TheDialogStyle,
      TheFooterStyle,
      TheFormStyle,
      TheHamburgerStyle,
      TheHeaderStyle,
      TheHtmlStyle,
      TheIconStyle,
      TheImageStyle,
      TheInfoStyle,
      TheInputStyle,
      TheLinkStyle,
      TheMainStyle,
      TheMenuStyle,
      ThePagerStyle,
      TheRootStyle,
      TheRouteStyle,
      TheRouterStyle,
      TheSectionStyle,
      TheSpinStyle,
      TheStepStyle,
      TheTabStyle,
      TheTableStyle,
      TheToastStyle,
      TheVideoStyle,
      TheViewStyle
    ].filter((Component) => Component.data).map((Component) => Component.data(options))
  )
}

TheThemeStyle.cssString = (options) => {
  const styles = TheThemeStyle.data(options)
  return styleString.fromStyles(styles)
}

TheThemeStyle.componentPaths = [
  '@the-/ui-alt/shim/TheAltStyle',
  '@the-/ui-bar/shim/TheBarStyle',
  '@the-/ui-body/shim/TheBodyStyle',
  '@the-/ui-button/shim/TheButtonStyle',
  '@the-/ui-caught/shim/TheCaughtStyle',
  '@the-/ui-condition/shim/TheConditionStyle',
  '@the-/ui-container/shim/TheContainerStyle',
  '@the-/ui-dialog/shim/TheDialogStyle',
  '@the-/ui-footer/shim/TheFooterStyle',
  '@the-/ui-form/shim/TheFormStyle',
  '@the-/ui-hamburger/shim/TheHamburgerStyle',
  '@the-/ui-header/shim/TheHeaderStyle',
  '@the-/ui-html/shim/TheHtmlStyle',
  '@the-/ui-icon/shim/TheIconStyle',
  '@the-/ui-image/shim/TheImageStyle',
  '@the-/ui-info/shim/TheInfoStyle',
  '@the-/ui-input/shim/TheInputStyle',
  '@the-/ui-link/shim/TheLinkStyle',
  '@the-/ui-main/shim/TheMainStyle',
  '@the-/ui-menu/shim/TheMenuStyle',
  '@the-/ui-pager/shim/ThePagerStyle',
  '@the-/ui-root/shim/TheRootStyle',
  '@the-/ui-route/shim/TheRouteStyle',
  '@the-/ui-router/shim/TheRouterStyle',
  '@the-/ui-section/shim/TheSectionStyle',
  '@the-/ui-spin/shim/TheSpinStyle',
  '@the-/ui-step/shim/TheStepStyle',
  '@the-/ui-tab/shim/TheTabStyle',
  '@the-/ui-table/shim/TheTableStyle',
  '@the-/ui-toast/shim/TheToastStyle',
  '@the-/ui-video/shim/TheVideoStyle',
  '@the-/ui-view/shim/TheViewStyle',

]

export default TheThemeStyle
