// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/store
 * @version 15.4.5
 * @description Redux wrapper for the-framework
 * @typicalname store
 * @license MIT
 */
'use strict'

const TheStore_ = require('./TheStore')
const create_ = require('./create')
const helpers_ = require('./helpers')
const toStoreScopeClass_ = require('./toStoreScopeClass')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheStore = TheStore_
exports.create = create_
exports.helpers = helpers_
exports.toStoreScopeClass = toStoreScopeClass_

module.exports = default__
