// Code generated by coz. DO NOT EDIT.
/**
 * React components of THE framework
 * @module @the-/components
 */
'use strict'

const components_ = require('./components')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.components = components_

module.exports = {
  components: components_,
}
