// Code generated by coz. DO NOT EDIT.
/**
 * React components of THE framework
 * @module @the-/ui
 * @version 17.0.8
 */

'use strict'

exports.TheAlt = require('@the-/ui-alt/shim/TheAlt').default
exports.TheBar = require('@the-/ui-bar/shim/TheBar').default
exports.TheActionBar = require('@the-/ui-bar/shim/TheActionBar').default
exports.TheBody = require('@the-/ui-body/shim/TheBody').default
exports.TheButton = require('@the-/ui-button/shim/TheButton').default
exports.TheButtonGroup = require('@the-/ui-button/shim/TheButtonGroup').default
exports.TheCaught = require('@the-/ui-caught/shim/TheCaught').default
exports.TheCaughtCatcher = require('@the-/ui-caught/shim/TheCaughtCatcher').default
exports.TheCondition = require('@the-/ui-condition/shim/TheCondition').default
exports.TheContainer = require('@the-/ui-container/shim/TheContainer').default
exports.TheDialog = require('@the-/ui-dialog/shim/TheDialog').default
exports.TheOkDialog = require('@the-/ui-dialog/shim/TheOkDialog').default
exports.TheYesNoDialog = require('@the-/ui-dialog/shim/TheYesNoDialog').default
exports.TheConfirmDialog = require('@the-/ui-dialog/shim/TheConfirmDialog').default
exports.TheFooter = require('@the-/ui-footer/shim/TheFooter').default
exports.TheForm = require('@the-/ui-form/shim/TheForm').default
exports.TheFormBinder = require('@the-/ui-form/shim/TheFormBinder').default
exports.TheHamburger = require('@the-/ui-hamburger/shim/TheHamburger').default
exports.TheHead = require('@the-/ui-head/shim/TheHead').default
exports.TheHeader = require('@the-/ui-header/shim/TheHeader').default
exports.TheHtml = require('@the-/ui-html/shim/TheHtml').default
exports.TheIcon = require('@the-/ui-icon/shim/TheIcon').default
exports.TheImage = require('@the-/ui-image/shim/TheImage').default
exports.TheInfo = require('@the-/ui-info/shim/TheInfo').default
exports.TheInput = require('@the-/ui-input/shim/TheInput').default
exports.TheInputText = require('@the-/ui-input/shim/TheInputText').default
exports.TheInputTextArea = require('@the-/ui-input/shim/TheInputTextArea').default
exports.TheInputTag = require('@the-/ui-input/shim/TheInputTag').default
exports.TheInputUpload = require('@the-/ui-input/shim/TheInputUpload').default
exports.TheInputSearch = require('@the-/ui-input/shim/TheInputSearch').default
exports.TheInputRadio = require('@the-/ui-input/shim/TheInputRadio').default
exports.TheInputCheckbox = require('@the-/ui-input/shim/TheInputCheckbox').default
exports.TheInputSelect = require('@the-/ui-input/shim/TheInputSelect').default
exports.TheInputPassword = require('@the-/ui-input/shim/TheInputPassword').default
exports.TheInputToggle = require('@the-/ui-input/shim/TheInputToggle').default
exports.TheLink = require('@the-/ui-link/shim/TheLink').default
exports.TheMain = require('@the-/ui-main/shim/TheMain').default
exports.TheMenu = require('@the-/ui-menu/shim/TheMenu').default
exports.TheMenuItem = require('@the-/ui-menu/shim/TheMenuItem').default
exports.TheDropdownMenu = require('@the-/ui-menu/shim/TheDropdownMenu').default
exports.TheMeta = require('@the-/ui-meta/shim/TheMeta').default
exports.ThePager = require('@the-/ui-pager/shim/ThePager').default
exports.TheRoot = require('@the-/ui-root/shim/TheRoot').default
exports.TheRoute = require('@the-/ui-route/shim/TheRoute').default
exports.TheRouteStack = require('@the-/ui-route/shim/TheRouteStack').default
exports.TheRouter = require('@the-/ui-router/shim/TheRouter').default
exports.TheSection = require('@the-/ui-section/shim/TheSection').default
exports.TheAccordionSection = require('@the-/ui-section/shim/TheAccordionSection').default
exports.TheSpin = require('@the-/ui-spin/shim/TheSpin').default
exports.TheStep = require('@the-/ui-step/shim/TheStep').default
exports.TheStepBar = require('@the-/ui-step/shim/TheStepBar').default
exports.TheTab = require('@the-/ui-tab/shim/TheTab').default
exports.TheTable = require('@the-/ui-table/shim/TheTable').default
exports.TheToast = require('@the-/ui-toast/shim/TheToast').default
exports.TheToastGroup = require('@the-/ui-toast/shim/TheToastGroup').default
exports.TheVideo = require('@the-/ui-video/shim/TheVideo').default
exports.TheView = require('@the-/ui-view/shim/TheView').default
