// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Utility for bin
 * @license MIT
 * @module @the-/util-bin
 * @typicalname utilBin
 * @version 15.4.12
 */
'use strict'

const hasBin_ = require('./hasBin')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.hasBin = hasBin_

module.exports = {
  hasBin: hasBin_,
}
