// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck
/**
 * @access protected
 * @description Helper functions
 * @memberOf module:@the-/support
 * @namespace helpers
 */
'use strict'

const detectUnsupportedCode_ = require('./detectUnsupportedCode')
const findEvalCode_ = require('./findEvalCode')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.detectUnsupportedCode = detectUnsupportedCode_
exports.findEvalCode = findEvalCode_

module.exports = {
  detectUnsupportedCode: detectUnsupportedCode_,
  findEvalCode: findEvalCode_,
}
