// Code generated by coz. DO NOT EDIT.
/**
 * Repeatable of the-component
 * @module the-repeatable
 */
'use strict'

import TheRepeatable from './TheRepeatable'
import TheRepeatableStyle from './TheRepeatableStyle'

export {
 TheRepeatable,
 TheRepeatableStyle,
}
