// Code generated by coz. DO NOT EDIT.
/**
 * @description Utility for client side
 * @license MIT
 * @module @the-/util-client
 * @typicalname utilClient
 * @version 15.4.7
 */
'use strict'

const readFile_ = require('./readFile')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.readFile = readFile_

module.exports = {
  readFile: readFile_,
}
