// Code generated by coz. DO NOT EDIT.
/**
 * Route of the-components
 * @module the-route
 */
'use strict'

import TheRoute from './TheRoute'
import TheRouteStack from './TheRouteStack'
import TheRouteStyle from './TheRouteStyle'

export {
 TheRoute,
 TheRouteStack,
 TheRouteStyle,
}
