// Code generated by coz. DO NOT EDIT.
/**
 * Route of the-components
 * @module @the-/route
 */
'use strict'

const TheRoute_ = require('./TheRoute')
const TheRouteStack_ = require('./TheRouteStack')
const TheRouteStyle_ = require('./TheRouteStyle')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRoute = TheRoute_
exports.TheRouteStack = TheRouteStack_
exports.TheRouteStyle = TheRouteStyle_

module.exports = {
  TheRoute: TheRoute_,
  TheRouteStack: TheRouteStack_,
  TheRouteStyle: TheRouteStyle_,
}
