// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/date
 * @version 15.4.2
 * @description Date utility for the-framework
 * @typicalname date
 * @license MIT
 */
'use strict'

const Durations_ = require('./Durations')
const TheDate_ = require('./TheDate')
const Timezones_ = require('./Timezones')
const create_ = require('./create')
const mixins_ = require('./mixins')
const units_ = require('./units')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Durations = Durations_
exports.TheDate = TheDate_
exports.Timezones = Timezones_
exports.create = create_
exports.mixins = mixins_
exports.units = units_

module.exports = default__
