// Code generated by coz. DO NOT EDIT.
/**
 * @description Secret store for the-frameworks
 * @license MIT
 * @module @the-/secret
 * @typicalname secret
 * @version 15.4.7
 */
'use strict'

const TheSecret_ = require('./TheSecret')
const create_ = require('./create')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSecret = TheSecret_
exports.create = create_
exports.mixins = mixins_

module.exports = default__
