// Code generated by coz. DO NOT EDIT.
'use strict'

const ChannelNames = Object.freeze(
 /**
  * ChannelNames
  * @memberof module:@the-/rtc.constants
  * @module ChannelNames
  */
  {
    DEFAULT_CHANNEL: 'default',
    PUB_SUB_CHANNEL: 'pub-sub',
    STREAM_CHANNEL: 'stream',
    STREAM_CONTROL_CHANNEL: 'stream-control',
  },
)

module.exports = ChannelNames
