// Code generated by coz. DO NOT EDIT.
/**
 * @memberof module:@the-/rtc
 * @description Constant variables
 * @namespace constants
 */
'use strict'

const ChannelNames_ = require('./ChannelNames')
const IOEvents_ = require('./IOEvents')
const PeerEvents_ = require('./PeerEvents')
const PeerPurposes_ = require('./PeerPurposes')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ChannelNames = ChannelNames_
exports.IOEvents = IOEvents_
exports.PeerEvents = PeerEvents_
exports.PeerPurposes = PeerPurposes_

module.exports = {
  ChannelNames: ChannelNames_,
  IOEvents: IOEvents_,
  PeerEvents: PeerEvents_,
  PeerPurposes: PeerPurposes_,
}
