// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Axe for the-framework
 * @license MIT
 * @module @the-/axe
 * @typicalname axe
 * @version 15.6.9
 */
'use strict'

const Logger_ = require('./Logger')
const TheAxe_ = require('./TheAxe')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Logger = Logger_
exports.TheAxe = TheAxe_
exports.create = create_

module.exports = default__
