// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-calendar
 * @typicalname uiCalendar
 * @version 15.4.2
 * @description Calendar of the-components
 */
'use strict'

import TheCalendar from './TheCalendar'
import TheCalendarStyle from './TheCalendarStyle'

export {
  TheCalendar,
  TheCalendarStyle,
}

export default {
  TheCalendar,
  TheCalendarStyle,
}
