// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Calendar of the-components
 * @module @the-/ui-calendar
 * @typicalname uiCalendar
 * @version 16.0.1
 */
'use strict'

import TheCalendar from './TheCalendar'

export {
  TheCalendar,
}
