// Code generated by coz. DO NOT EDIT.
/**
 * Live demo of the-components
 * @module @the-/component-demo
 */
'use strict'

import TheComponentDemo from './TheComponentDemo'

export {
  TheComponentDemo,
}

export default {
      TheComponentDemo,
}
