// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck
/**
 * @access protected
 * @description Constant variables
 * @memberOf module:@the-/code
 * @namespace constants
 */
'use strict'

const TypeNamings_ = require('./TypeNamings')
const Types_ = require('./Types')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TypeNamings = TypeNamings_
exports.Types = Types_

module.exports = {
  TypeNamings: TypeNamings_,
  Types: Types_,
}
