// Code generated by coz. DO NOT EDIT.
/**
 * @description Mixin functions
 * @memberOf module:@the-/scene
 * @namespace mixins
 */
'use strict'

const errorMix_ = require('./errorMix')
const goMix_ = require('./goMix')
const subMix_ = require('./subMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.errorMix = errorMix_
exports.goMix = goMix_
exports.subMix = subMix_

module.exports = {
  errorMix: errorMix_,
  goMix: goMix_,
  subMix: subMix_,
}
