// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-sw
 * @version 15.4.0
 * @description Utility for service workers
 * @typicalname utilSw
 * @license MIT
 */
'use strict'

const appCache_ = require('./appCache')
const cachingFetch_ = require('./cachingFetch')
const parseUrl_ = require('./parseUrl')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.appCache = appCache_
exports.cachingFetch = cachingFetch_
exports.parseUrl = parseUrl_

module.exports = {
  appCache: appCache_,
  cachingFetch: cachingFetch_,
  parseUrl: parseUrl_,
}
