// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/demo-ui
 * @typicalname demoUi
 * @version 15.4.0
 * @description Demo of the-components
 */
'use strict'

import TheDemoUi from './TheDemoUi'
import TheDemoUiStyle from './TheDemoUiStyle'

export {
  TheDemoUi,
  TheDemoUiStyle,
}

export default {
  TheDemoUi,
  TheDemoUiStyle,
}
