// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Demo of the-components
 * @module @the-/demo-ui
 * @typicalname demoUi
 * @version 15.4.13
 */
'use strict'

import TheDemoUi from './TheDemoUi'
import TheDemoUiStyle from './TheDemoUiStyle'

export {
  TheDemoUi,
  TheDemoUiStyle,
}
