// Code generated by coz. DO NOT EDIT.
/**
 * @namespace constants
 * @memberOf module:@the-/state
 * @access protected
 * @description Constant namespaces
 */
'use strict'

const ActionTypes_ = require('./ActionTypes')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ActionTypes = ActionTypes_

module.exports = {
  ActionTypes: ActionTypes_,
}
