// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module mixins
 */
'use strict'

const lockMix_ = require('./lockMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.lockMix = lockMix_

module.exports = {
  lockMix: lockMix_,
}
