// Code generated by coz. DO NOT EDIT.
/**
 * @desc Mix functions
 * @namespace mixins
 * @memberOf module:@the-/setting
 */
'use strict'

const lockMix_ = require('./lockMix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.lockMix = lockMix_

module.exports = {
  lockMix: lockMix_,
}
