// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Table for the-components
 * @module @the-/ui-table
 * @typicalname uiTable
 * @version 17.0.2
 */
'use strict'

import TheTable from './TheTable'

export {
  TheTable,
}
