// Code generated by coz. DO NOT EDIT.
/**
 * @description Table for the-components
 * @module @the-/ui-table
 * @typicalname uiTable
 * @version 15.4.8
 */
'use strict'

import TheTable from './TheTable'
import TheTableStyle from './TheTableStyle'

export {
  TheTable,
  TheTableStyle,
}

export default {
  TheTable,
  TheTableStyle,
}
