// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Facade to wrap contexts
 * @license MIT
 * @module @the-/facade-context
 * @typicalname facadeContext
 * @version 16.0.8
 */
'use strict'

const storeLoaderFor_ = require('./storeLoaderFor')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.storeLoaderFor = storeLoaderFor_

module.exports = {
  storeLoaderFor: storeLoaderFor_,
}
