// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/ui-list
 * @typicalname uiList
 * @version 15.4.4
 * @description List of the-components
 */
'use strict'

import TheList from './TheList'
import TheListGroup from './TheListGroup'
import TheListItem from './TheListItem'
import TheListStyle from './TheListStyle'

export {
  TheList,
  TheListGroup,
  TheListItem,
  TheListStyle,
}

export default {
  TheList,
  TheListGroup,
  TheListItem,
  TheListStyle,
}
