// Code generated by coz. DO NOT EDIT.
/**
 * @description User media handler
 * @license MIT
 * @module @the-/media
 * @typicalname media
 * @version 15.5.1
 */
'use strict'

const TheMedia_ = require('./TheMedia')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheMedia = TheMedia_
exports.create = create_

module.exports = default__
