// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Style of the-components
 * @module @the-/ui-style
 * @typicalname uiStyle
 * @version 16.0.2
 */
'use strict'

import TheStyle from './TheStyle'

export {
  TheStyle,
}
