// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Utility for string
 * @license MIT
 * @module @the-/util-string
 * @typicalname utilString
 * @version 15.4.15
 */
'use strict'

const isEmail_ = require('./isEmail')
const isImageUrl_ = require('./isImageUrl')
const isPhoneNumber_ = require('./isPhoneNumber')
const isUrl_ = require('./isUrl')
const isVideoUrl_ = require('./isVideoUrl')
const normalizeString_ = require('./normalizeString')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.isEmail = isEmail_
exports.isImageUrl = isImageUrl_
exports.isPhoneNumber = isPhoneNumber_
exports.isUrl = isUrl_
exports.isVideoUrl = isVideoUrl_
exports.normalizeString = normalizeString_

module.exports = {
  isEmail: isEmail_,
  isImageUrl: isImageUrl_,
  isPhoneNumber: isPhoneNumber_,
  isUrl: isUrl_,
  isVideoUrl: isVideoUrl_,
  normalizeString: normalizeString_,
}
