// Code generated by coz. DO NOT EDIT.
/**
 * S3 upload helper
 * @module @the-/s3
 */
'use strict'

const TheS3_ = require('./TheS3')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheS3 = TheS3_
exports.create = create_

module.exports = default__
