// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description S3 upload helper
 * @license MIT
 * @module @the-/s3
 * @typicalname s3
 * @version 15.5.11
 */
'use strict'

const TheS3_ = require('./TheS3')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheS3 = TheS3_
exports.create = create_

module.exports = default__
