// Code generated by coz. DO NOT EDIT.
/**
 * Assert functions
 * @module assert
 */
'use strict'

const assertMethods_ = require('./assertMethods')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.assertMethods = assertMethods_

module.exports = {
  assertMethods: assertMethods_,
}
