// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Helpers
 * @memberof module:@the-/rtc
 * @namespace helpers
 */
'use strict'

const createHTTPServer_ = require('./createHTTPServer')
const handleUnknownKeys_ = require('./handleUnknownKeys')
const parseTurnSecret_ = require('./parseTurnSecret')
const waitChannelOpen_ = require('./waitChannelOpen')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.createHTTPServer = createHTTPServer_
exports.handleUnknownKeys = handleUnknownKeys_
exports.parseTurnSecret = parseTurnSecret_
exports.waitChannelOpen = waitChannelOpen_

module.exports = {
  createHTTPServer: createHTTPServer_,
  handleUnknownKeys: handleUnknownKeys_,
  parseTurnSecret: parseTurnSecret_,
  waitChannelOpen: waitChannelOpen_,
}
