// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Html of the-components
 * @module @the-/ui-html
 * @typicalname uiHtml
 * @version 16.0.0
 */
'use strict'

import TheHtml from './TheHtml'

export {
  TheHtml,
}
