// Code generated by coz. DO NOT EDIT.
/**
 * @description Html of the-components
 * @module @the-/ui-html
 * @typicalname uiHtml
 * @version 15.4.5
 */
'use strict'

import TheHtml from './TheHtml'
import TheHtmlStyle from './TheHtmlStyle'

export {
  TheHtml,
  TheHtmlStyle,
}

export default {
  TheHtml,
  TheHtmlStyle,
}
