// Code generated by coz. DO NOT EDIT.
/**
 * Link of the-components
 * @module @the-/link
 */
'use strict'

import TheLink from './TheLink'
import TheLinkStyle from './TheLinkStyle'

export {
  TheLink,
  TheLinkStyle,
}
