// Code generated by coz. DO NOT EDIT.
/**
 * Geo location utility
 * @module the-geo
 */
'use strict'

const TheGeo_ = require('./TheGeo')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheGeo = TheGeo_
exports.create = create_

module.exports = default__
