// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Async lock
 * @license MIT
 * @module @the-/lock
 * @typicalname lock
 * @version 15.4.9
 */
'use strict'

const TheLock_ = require('./TheLock')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheLock = TheLock_

module.exports = default__
