// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/mixin-scene
 * @version 15.4.5
 * @description Mixins for the-scene
 * @typicalname mixinScene
 * @license MIT
 */
'use strict'

const bindDefaults_ = require('./bindDefaults')
const bindScope_ = require('./bindScope')
const helpers_ = require('./helpers')
const siteToast_ = require('./siteToast')
const withBack_ = require('./withBack')
const withBusy_ = require('./withBusy')
const withEntities_ = require('./withEntities')
const withEntry_ = require('./withEntry')
const withFailure_ = require('./withFailure')
const withFilter_ = require('./withFilter')
const withForm_ = require('./withForm')
const withHistory_ = require('./withHistory')
const withId_ = require('./withId')
const withLimit_ = require('./withLimit')
const withLocation_ = require('./withLocation')
const withPage_ = require('./withPage')
const withQuery_ = require('./withQuery')
const withReady_ = require('./withReady')
const withResult_ = require('./withResult')
const withSort_ = require('./withSort')
const withTargets_ = require('./withTargets')
const withValues_ = require('./withValues')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.bindDefaults = bindDefaults_
exports.bindScope = bindScope_
exports.helpers = helpers_
exports.siteToast = siteToast_
exports.withBack = withBack_
exports.withBusy = withBusy_
exports.withEntities = withEntities_
exports.withEntry = withEntry_
exports.withFailure = withFailure_
exports.withFilter = withFilter_
exports.withForm = withForm_
exports.withHistory = withHistory_
exports.withId = withId_
exports.withLimit = withLimit_
exports.withLocation = withLocation_
exports.withPage = withPage_
exports.withQuery = withQuery_
exports.withReady = withReady_
exports.withResult = withResult_
exports.withSort = withSort_
exports.withTargets = withTargets_
exports.withValues = withValues_

module.exports = {
  bindDefaults: bindDefaults_,
  bindScope: bindScope_,
  helpers: helpers_,
  siteToast: siteToast_,
  withBack: withBack_,
  withBusy: withBusy_,
  withEntities: withEntities_,
  withEntry: withEntry_,
  withFailure: withFailure_,
  withFilter: withFilter_,
  withForm: withForm_,
  withHistory: withHistory_,
  withId: withId_,
  withLimit: withLimit_,
  withLocation: withLocation_,
  withPage: withPage_,
  withQuery: withQuery_,
  withReady: withReady_,
  withResult: withResult_,
  withSort: withSort_,
  withTargets: withTargets_,
  withValues: withValues_,
}
