// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Mixins for the-scene
 * @license MIT
 * @module @the-/mixin-scene
 * @typicalname mixinScene
 * @version 17.1.4
 */
'use strict'

const bindDefaults_ = require('./bindDefaults')
const bindScope_ = require('./bindScope')
const helpers_ = require('./helpers')
const withBusy_ = require('./withBusy')
const withEntities_ = require('./withEntities')
const withEntry_ = require('./withEntry')
const withFilter_ = require('./withFilter')
const withLimit_ = require('./withLimit')
const withPage_ = require('./withPage')
const withQuery_ = require('./withQuery')
const withReady_ = require('./withReady')
const withResult_ = require('./withResult')
const withSort_ = require('./withSort')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.bindDefaults = bindDefaults_
exports.bindScope = bindScope_
exports.helpers = helpers_
exports.withBusy = withBusy_
exports.withEntities = withEntities_
exports.withEntry = withEntry_
exports.withFilter = withFilter_
exports.withLimit = withLimit_
exports.withPage = withPage_
exports.withQuery = withQuery_
exports.withReady = withReady_
exports.withResult = withResult_
exports.withSort = withSort_

module.exports = {
  bindDefaults: bindDefaults_,
  bindScope: bindScope_,
  helpers: helpers_,
  withBusy: withBusy_,
  withEntities: withEntities_,
  withEntry: withEntry_,
  withFilter: withFilter_,
  withLimit: withLimit_,
  withPage: withPage_,
  withQuery: withQuery_,
  withReady: withReady_,
  withResult: withResult_,
  withSort: withSort_,
}
