// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Link of the-components
 * @module @the-/ui-link
 * @typicalname uiLink
 * @version 15.4.10
 */
'use strict'

import TheLink from './TheLink'
import TheLinkStyle from './TheLinkStyle'

export {
  TheLink,
  TheLinkStyle,
}

export default {
  TheLink,
  TheLinkStyle,
}
