// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Link of the-components
 * @module @the-/ui-link
 * @typicalname uiLink
 * @version 16.0.3
 */
'use strict'

import TheLink from './TheLink'

export {
  TheLink,
}
