// Code generated by coz. DO NOT EDIT.
/**
 * Head of the-components
 * @module @the-/ui-head
 */
'use strict'

import TheHead from './TheHead'

export {
  TheHead,
}

export default {
      TheHead,
}
