// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Head of the-components
 * @module @the-/ui-head
 * @typicalname uiHead
 * @version 15.4.12
 */
'use strict'

import TheHead from './TheHead'

export {
  TheHead,
}
