// Code generated by coz. DO NOT EDIT.
/**
 * @description Lint of the-frameworks
 * @license MIT
 * @module @the-/lint
 * @typicalname lint
 * @version 15.4.20
 */
'use strict'

const TheLint_ = require('./TheLint')
const create_ = require('./create')
const helpers_ = require('./helpers')
const rules_ = require('./rules')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheLint = TheLint_
exports.create = create_
exports.helpers = helpers_
exports.rules = rules_

module.exports = default__
