// Code generated by coz. DO NOT EDIT.
/**
 * View of the-components
 * @module the-view
 */
'use strict'

import TheView from './TheView'
import TheViewStyle from './TheViewStyle'

export {
 TheView,
 TheViewStyle,
}
