// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @access protected
 * @description Mixin functions
 * @memberOf module:@the-/video-converter
 * @namespace mixins
 */
'use strict'

const mp4Mix_ = require('./mp4Mix')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.mp4Mix = mp4Mix_

module.exports = {
  mp4Mix: mp4Mix_,
}
