// Code generated by coz. DO NOT EDIT.
/**
 * Constant variables
 * @module constants
 */
'use strict'

const AppConsts_ = require('./AppConsts')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.AppConsts = AppConsts_

module.exports = {
  AppConsts: AppConsts_,
}
