// Code generated by coz. DO NOT EDIT.
/**
 * @description Message pack wrapper for the-components
 * @license MIT
 * @module @the-/pack
 * @typicalname pack
 * @version 15.4.9
 */
'use strict'

const Converters_ = require('./Converters')
const ThePack_ = require('./ThePack')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.Converters = Converters_
exports.ThePack = ThePack_
exports.create = create_

module.exports = default__
