// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Message pack wrapper for the-components
 * @license MIT
 * @module @the-/pack
 * @typicalname pack
 * @version 16.0.6
 */
'use strict'

const ThePack_ = require('./ThePack')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ThePack = ThePack_
exports.create = create_

module.exports = default__
