// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Base class of the-scene
 * @license MIT
 * @module @the-/scene
 * @typicalname scene
 * @version 16.0.2
 */
'use strict'

const TheScene_ = require('./TheScene')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheScene = TheScene_
exports.create = create_

module.exports = default__
