// Code generated by coz. DO NOT EDIT.
/**
 * @description Base class of the-scene
 * @license MIT
 * @module @the-/scene
 * @typicalname scene
 * @version 15.4.7
 */
'use strict'

const TheScene_ = require('./TheScene')
const create_ = require('./create')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheScene = TheScene_
exports.create = create_
exports.mixins = mixins_

module.exports = default__
