// Code generated by coz. DO NOT EDIT.
/**
 * @description Shared value manager
 * @license MIT
 * @module @the-/seat
 * @typicalname seat
 * @version 15.4.8
 */
'use strict'

const TheSeat_ = require('./TheSeat')
const create_ = require('./create')
const helpers_ = require('./helpers')
const mixins_ = require('./mixins')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheSeat = TheSeat_
exports.create = create_
exports.helpers = helpers_
exports.mixins = mixins_

module.exports = default__
