// Code generated by coz. DO NOT EDIT.
/**
 * @description Signature pad of the-components
 * @module @the-/ui-signature
 * @typicalname uiSignature
 * @version 15.4.8
 */
'use strict'

import TheSignature from './TheSignature'
import TheSignatureInput from './TheSignatureInput'
import TheSignatureStyle from './TheSignatureStyle'

export {
  TheSignature,
  TheSignatureInput,
  TheSignatureStyle,
}

export default {
  TheSignature,
  TheSignatureInput,
  TheSignatureStyle,
}
