// Code generated by coz. DO NOT EDIT.
/**
 * Signature pad of the-components
 * @module @the-/ui-signature
 */
'use strict'

import TheSignature from './TheSignature'
import TheSignatureInput from './TheSignatureInput'
import TheSignatureStyle from './TheSignatureStyle'

export {
  TheSignature,
  TheSignatureInput,
  TheSignatureStyle,
}

export default {
  TheSignature,
  TheSignatureInput,
  TheSignatureStyle,
}
