// Code generated by coz. DO NOT EDIT.
/**
 * Array utility of the-framework
 * @module the-array
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const keyPathMap_ = require('./keyPathMap')
const randomFind_ = require('./randomFind')
const shuffleSort_ = require('./shuffleSort')
const sumReducer_ = require('./sumReducer')
const uniqueFilter_ = require('./uniqueFilter')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.keyPathMap = _d(keyPathMap_)
exports.randomFind = _d(randomFind_)
exports.shuffleSort = _d(shuffleSort_)
exports.sumReducer = _d(sumReducer_)
exports.uniqueFilter = _d(uniqueFilter_)

module.exports = Object.freeze({
  keyPathMap: _d(keyPathMap_),
  randomFind: _d(randomFind_),
  shuffleSort: _d(shuffleSort_),
  sumReducer: _d(sumReducer_),
  uniqueFilter: _d(uniqueFilter_),
})
