// Code generated by coz. DO NOT EDIT.
/**
 * @module @the-/util-array
 * @version 15.4.5
 * @description Array utility of the-framework
 * @typicalname utilArray
 * @license MIT
 */
'use strict'

const keyPathMap_ = require('./keyPathMap')
const randomFind_ = require('./randomFind')
const shuffleSort_ = require('./shuffleSort')
const sumReducer_ = require('./sumReducer')
const uniqueFilter_ = require('./uniqueFilter')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.keyPathMap = keyPathMap_
exports.randomFind = randomFind_
exports.shuffleSort = shuffleSort_
exports.sumReducer = sumReducer_
exports.uniqueFilter = uniqueFilter_

module.exports = {
  keyPathMap: keyPathMap_,
  randomFind: randomFind_,
  shuffleSort: shuffleSort_,
  sumReducer: sumReducer_,
  uniqueFilter: uniqueFilter_,
}
