// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Script runner for the-framework
 * @license MIT
 * @module @the-/run
 * @typicalname run
 * @version 15.6.2
 */
'use strict'

const TheRun_ = require('./TheRun')
const create_ = require('./create')
const run_ = require('./run')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheRun = TheRun_
exports.create = create_
exports.run = run_

module.exports = default__
